### ISSUE TITLE
[RFE] Adding CI checks for toolbox in podman

### ISSUE THREAD

**Issue by travier** [containers/podman#10296]
/kind feature

**Description**

containers/toolbox is a popular (in Fedora CoreOS & Fedora Silverblue) downstream user of podman and has been broken several times by podman updates. We have CI checks now in Fedora CoreOS and soon in toolbox itself but it would be even better if you could run the toolbox test suite on podman at least once before releases or directly in CI.

I'll be setting up toolbox CI on Fedora CoreOS soon so feel free to reach out.

Non-exhaustive list of issues:
https://github.com/containers/podman/issues/10274
https://github.com/containers/podman/pull/10288
https://github.com/coreos/fedora-coreos-tracker/issues/734

**Comment by mheon** [comment]
We do have a number of CI checks added by the Toolbox team previously, but I don't believe any of them use Toolbox itself, but instead test the ways Toolbox uses Podman. We are definitely not opposed to adding to this suite.

I think @baude was opposed to having Toolbox tests gate Podman changes, but I could be misremembering here.

**Comment by rhatdan** [comment]
Yes, we would be fine with gating our release, but would be reluctant on every PR, unless they are specific to Podman, like we currently have.  This issue would be making sure toolbox breakage did not block Podman PRs being merged, which we have seen in CI systems in the past.

**Comment by baude** [comment]
I just want to reply for the record given @mheon comment.  This has been an ongoing discussion with the TB team.  We actually were not opposed to running their tests in our CI for every PR, but in the same breath, we also were not going to have the tests be blockers.  I think most podman contributors who saw a busted test would give it a look-see and see about fixing it, but it wouldn't be required.

I think that offer is still quite reasonable.  The TB team was supposed to provide us with their tests so that we could create a CI instance and run it.  That offer is still open.  Ideally they would integrate it themselves with a PR but we could also assist happily.

One last item we also agreed on as well.  If we cannot figure out why a test is failing AND it lingers due to something like unavailibility, we would temporarily take the tests offline because we pay for our CI resources.

Bottom line for me ... lets get the tests running in our CI.  If someone outside our team can do the work, then it can be done as soon as the tests are ready.  If not, I'll prioritize amongst all the things we have on our plate (as in, it will get done as we catch up).

Thanks for taking this up!

**Comment by matthiasclasen** [comment]
Let me translate how 'we don't want this to be a blocker' reads from the other side:

We like to continue breaking your stuff.

That is very disappointing.

**Comment by garrett** [comment]
I agree with @matthiasclasen.

---

I've been using Silverblue for a while now (almost 2 years) and it's generally fine, except for numerous toolbox issues. Almost all of the Toolbox issues have come from Podman breaking things in version bumps.

Like most others using Silverblue, having Toolbox and/or Podman not working prevents me from actually doing work until I fix it, as everything I work on is inside of a Toolbox container for development. (Generally, the fix is to roll back to the previous deployment of Silverblue, apply a hotfix from bodhi as an override replace, and/or nuke all my containers and rebuild my dev environment — which _I_ thankfully have scripted, but others don't.)

Some of these have happened in beta, but a worrying amount of them have hit released versions.

There definitely needs to be some CI _somewhere_ that would prevent a broken podman+toolbox combo from making its way into Silverblue. (Ideally, it would not make it into normal Fedora Workstation/Server either, as people do rely on toolbox and podman working there as well, but it's usually not quite as critical as it is in Silverblue.)

It makes sense to try to catch these issues as early as possible, so having a "does it break toolbox?" test would be beneficial.

(We've also hit a handful of Podman stability issues in [Cockpit-Podman](https://github.com/cockpit-project/cockpit-podman) as well, but that's a different, but somewhat related topic.)

**Comment by debarshiray** [comment]
The consensus was:

1. We will add unit tests to Podman's own upstream test suite that mimics the ways in which Toolbox uses Podman. These would get run on each pull request, be blocking, etc.. We have done that over time, and we need to keep adding more as the code evolves and bugs are found, etc..
2. Get Toolbox's upstream test suite run as part of Podman's Fedora gating. This is the *get Toolbox tests added to Podman* part. @edsantiago was helping @HarryMichal with this, but I think it got stuck somewhere in the complexities of Fedora gating.

I think an important aspect here is that the [latest regression](https://github.com/containers/podman/issues/10274) involving the `PidFile` is about backwards compatibility with older Podman releases. This is generally a more difficult thing to test against, and something that affects Toolbox a lot because of the containers being treated as *pets*.

(There are tests in Podman that test upgrades, and in fact there was a test that could have caught it, but it was disabled because it wasn't obvious how to get it to work. [Looks](https://github.com/containers/podman/pull/10288) like that's getting fixed now.)

In Toolbox, so far, we have relied upon manual code review and testing to protect backwards compatibility. I think that we should devote a bit more attention to have better automated tests for upgrades in the future.

**Comment by mheon** [comment]
Normally we work with the Toolbox team to ensure that each Podman release
is tested and working before it reaches stable. This release was an early
RC that slipped in through a series of errors. The normal process should
have caught this one.

This doesn’t mean we shouldn’t improve gating and upstream CI, but this RC
slipping out was an anomaly and I don’t expect it to happen again - the
process will improve to prevent it.

**Comment by baude** [comment]
@debarshiray you are exactly correct (and I stand corrected), it was gating tests that we targeted. And shy of the anomaly as @mheon describes, that shouild sufficiently satisfy both parties.  Thank you for the clarification.  And! The gating IS blocking, so that should satisfy folks here.

**Comment by edsantiago** [comment]
I've dropped the ball on this too. I was waiting for my requirements. My requirements are:
- [x] an rpm package named `toolbox-tests`
- [x] that provides `/usr/share/toolbox/test/system/` containing one or more `*.bats` files
- [ ] and also all RPM `Requires` needed to run said tests (I don't know if this requirement is met, because)
- [ ] Once installed, a user (root or rootless as needed) can run `bats /usr/share/toolbox/test/system`, while cd'ed to any random directory (not just the test directory), and all tests will pass.

As of this writing, `toolbox-tests-0.0.99.1-1.fc34` does not meet the last requirement:
```console
# bats /usr/share/toolbox/test/system/
bats: libs/bats-support/load does not exist [message repeated a total of 7 times]
 ✗
   (from function `source' in file /usr/share/toolbox/test/system/001-version.bats, line 3,
    from function `bats_run_setup_file' in file /usr/libexec/bats-core/bats-exec-file, line 87,
    from function `main' in test file /usr/libexec/bats-core/bats-exec-file, line 258)
     `bats_run_setup_file' failed
...
```
This is beyond my ability to fix. Once it is fixed, please let me know and I will work to hook toolbox-tests into podman fedora gating. Thanks!

**Comment by HarryMichal** [comment]
>     * [ ]  Once installed, a user (root or rootless as needed) can run `bats /usr/share/toolbox/test/system`, while cd'ed to any random directory (not just the test directory), and all tests will pass.

I just [landed](https://github.com/containers/toolbox/pull/565) a fix for this. I'll discuss with @debarshiray making a new release with the fix included.

Still, I know the tests will not work locally, since in the tests we rely on some functionality that is backed by the exact testing environment (Zuul). I'll have to amend that to make the tests executable on other systems.

**Comment by HarryMichal** [comment]
The tests should be fairly easy to run now since I merged https://github.com/containers/toolbox/pull/774. I used the PR extensively on a FCOS host. So, after this I'll just update the test README and the `Requires` in the RPM package.

**Comment by rhatdan** [comment]
@debarshiray @garrett What is going on with this?

**Comment by HarryMichal** [comment]
Toolbox has a new release (v0.0.99.2) that fixes the tool-related problems @edsantiago mentioned.

The tests themselves are completely functional but still have a few downsides:

- are destructive (run `podman system reset` with default settings)
- depend on `bats-support` and `bats-assert` which are not packaged in Fedora (need to be set up manually)

The rpm is not ready due to missing `Requires` and the missing dependencies. It is being worked on.

**Comment by edsantiago** [comment]
>depend on bats-support and bats-assert which are not packaged in Fedora (need to be set up manually)

That's sort of a big hassle. I don't think podman gating tests should be in the business of managing and installing non-rpm content. At this point I consider this a showstopper.

I just installed `toolbox-tests-0.0.99.2-1.fc35.x86_64` and am still seeing the same errors I reported on May 12, presumably due to this bats-* requirement.

**Comment by HarryMichal** [comment]
> >depend on bats-support and bats-assert which are not packaged in Fedora (need to be set up manually)
> 
> That's sort of a big hassle. I don't think podman gating tests should be in the business of managing and installing non-rpm content. At this point I consider this a showstopper.

Agreed.

> I just installed `toolbox-tests-0.0.99.2-1.fc35.x86_64` and am still seeing the same errors I reported on May 12, presumably due to this bats-* requirement.

Right. This is related to the fact that the two libraries are not packaged, yet.

I remember you trying to run the tests some time ago and bumping into an issue with your current folder not being inside of the container causing the command to error out. That should be fixed now.

**Comment by edsantiago** [comment]
@HarryMichal it looks like bats-support is licensed as [Creative Commons](https://github.com/bats-core/bats-support/blob/master/LICENSE), could you just include the necessary files in your `-tests` rpm?

**Comment by HarryMichal** [comment]
> @HarryMichal it looks like bats-support is licensed as [Creative Commons](https://github.com/bats-core/bats-support/blob/master/LICENSE), could you just include the necessary files in your `-tests` rpm?

Aaah, that should work. I'll do it that way then.

**Comment by HarryMichal** [comment]
@edsantiago We've got a build in Fedora Rawhide that should contain all the pieces to make the system tests runnable. The build is already in stable so either wait for it to become available to you or get it from [koji](https://koji.fedoraproject.org/koji/taskinfo?taskID=72853363). The build is based on a snapshot of main, so any changes can be easily made.

**Comment by edsantiago** [comment]
>The build is already in stable

I'm not seeing that. I see .0.99.2-1.fc35 (from June) in stable. I downloaded the koji build you cited, but can't install:
```
  - nothing provides glibc >= 2.33.9000-54.fc35 needed by toolbox-0.0.99.2^1.git9820550c82bb-1.fc35.x86_64
```

**Comment by HarryMichal** [comment]
By stable I meant available via `dnf` in Rawhide. I suspect you tried to install the package on Fedora 34?

**Comment by edsantiago** [comment]
No, I was on Rawhide. I'm pretty sure it's not in stable nor updates-testing.

**Comment by HarryMichal** [comment]
Well, the build is still very fresh. I'm merely reporting what [Bodhi says](https://bodhi.fedoraproject.org/updates/FEDORA-2021-67c627c9af). Curious about the glibc requirement, though. Will test it out.

**Comment by HarryMichal** [comment]
The `glibc` update should also be in stable according to [Bodhi](https://bodhi.fedoraproject.org/updates/FEDORA-2021-e4b7110efe). Maybe the change simply needs to propagate first.

**Comment by olivergs** [comment]
@edsantiago Ok. Seems the toolbox package will need to wait for the next compose, but now the glibc package has landed and you should be able to install our build manually.

**Comment by olivergs** [comment]
@edsantiago Be careful! the tests still reset podman images and containers (tests execute  podman system reset)

**Comment by edsantiago** [comment]
That's OK: this is CI. 

Are tests intended to run as root, or rootless? As root, they take a long time in Setup (~10m), then fail with:
```
 ✗ list: Run 'list' with zero toolbox's containers and images, but other image (the list should be empty)
   (from function `assert_success' in file /usr/share/toolbox/test/system/libs/bats-assert/src/assert.bash, line 114,
    from function `pull_distro_image' in file /usr/share/toolbox/test/system/libs/helpers.bash, line 139,
    in test file /usr/share/toolbox/test/system/102-list.bats, line 38)
     `pull_distro_image busybox' failed
   Failed to load image docker.io/library/busybox from cache /tmp/bats-run-5030/image-cache/busybox-toolbox

   -- command failed --
   status : 1
   output (2 lines):
     time="2021-07-29T08:39:19-04:00" level=info msg="Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled"
     time="2021-07-29T08:39:19-04:00" level=fatal msg="Error determining manifest MIME type for dir:/tmp/bats-run-5030/image-cache/busybox-toolbox: open /tmp/bats-run-5030/image-cache/busybox-toolbox/manifest.json: no such file or directory"
   --

```

**Comment by olivergs** [comment]
They are expected to run rootless. Anyway I'm doing a new build because there is a test that is not passing because of a missmatch in the sources. I will tell you when the new build is available

**Comment by olivergs** [comment]
Ok. After closer inspection, seems the built we sent you should not fail. I was wrongly doing my testing with an "unclean" machine, but with a clean one, it works without problems.

Anyway, I sent a new build but it now depends on another different version of glibc, so until next compose it will not be installable.

The new build URL is: https://koji.fedoraproject.org/koji/taskinfo?taskID=72907020

**Comment by edsantiago** [comment]
I don't understand your last comment. Rootless tests pretty much completely fail on toolbox-0.0.99.2^1.git9820550c82bb-1.fc35. I interpret your comment as saying that you found something broken in it, and have fixed it, and I will wait for the next build. If you need a failure log from all the failed rootless tests in the build I ran, lmk.

**Comment by olivergs** [comment]
Sorry for the confusion.

First of all. The tests are intended to run rootless.

About the new build:

With the first build we provided, I was running the tests after your last comment to check if all was going as expected. In my case I got errors in one of the tests (not the one you got), so I was taking a look to the output and after some inspection I thought it was wrong due to a source mismatch when I built the rawhide package.

I decided then to send a new build with the latest upstream, as it was working for @HarryMichal and me.

Then, after Koji finished the new build, I was about to check the new package in my Rawhide VM, and then, I found the real root of the problem with the previous version was that I had an "unclean" environment with a manually built  older version of toolbox in it. So the tests were failing because they were run with that older version located in /usr/local. After removal of that old toolbox version, I run the tests with the first build we provided to you and they worked perfectly.

On the other hand, as I sent a new build with the latest snapshot from upstream, I just informed you of the newer build. Both should work without problems.

I would suggest to just try with the latest build and if it continues failing when run as rootless, please give us that log so we can work to make it run.

Hope this clarify what I posted before.

**Comment by olivergs** [comment]
@edsantiago The latest toolbox build is available in rawhide today. I've checked the tests and they run without any errors.

https://gist.github.com/olivergs/e6a99cbdb4263724c00b1c940bc02b22

Tell us if it works for you or if there is something you need from us to push this forward.

**Comment by edsantiago** [comment]
```console
$ bats /usr/share/toolbox/test/system/
 ✓ test suite: Setup
 ✓ version: Check version using option --version
 ✓ help: Run command 'help'
 ✓ help: Use flag '--help' (it should show usage screen)
 ✓ help: Try to run toolbox with non-existent command (shows usage screen)
 ✓ help: Try to run toolbox with non-existent flag (shows usage screen)                                                                                 [0/4528]
 ✓ help: Try to run 'toolbox create' with non-existent flag (shows usage screen)
 ✓ help: Try to run 'toolbox enter' with non-existent flag (shows usage screen)
 ✓ help: Try to run 'toolbox help' with non-existent flag (shows usage screen)
 ✓ help: Try to run 'toolbox init-container' with non-existent flag (shows usage screen)
 ✓ help: Try to run 'toolbox list' with non-existent flag (shows usage screen)
 ✓ help: Try to run 'toolbox rm' with non-existent flag (shows usage screen)
 ✓ help: Try to run 'toolbox rmi' with non-existent flag (shows usage screen)
 ✓ help: Try to run 'toolbox run' with non-existent flag (shows usage screen)
 ✗ create: Create the default container
   (from function `assert_success' in file /usr/share/toolbox/test/system/libs/bats-assert/src/assert.bash, line 114,
    in test file /usr/share/toolbox/test/system/101-create.bats, line 21)
     `assert_success' failed
   REPOSITORY                                 TAG         IMAGE ID      CREATED      SIZE
   registry.fedoraproject.org/fedora-toolbox  35          30e2dd6cf22e  2 weeks ago  346 MB

   -- command failed --
   status : 1
   output : Error: failed to create container fedora-toolbox-35
   --

 ✗ create: Create a container with a valid custom name ('custom-containerName')
   (from function `assert_success' in file /usr/share/toolbox/test/system/libs/bats-assert/src/assert.bash, line 114,
    in test file /usr/share/toolbox/test/system/101-create.bats, line 29)
     `assert_success' failed

   -- command failed --
   status : 1
   output : Error: failed to create container custom-containerName
   --

 ✗ create: Create a container with a custom image and name ('fedora32'; f32)
   (from function `assert_success' in file /usr/share/toolbox/test/system/libs/bats-assert/src/assert.bash, line 114,
    in test file /usr/share/toolbox/test/system/101-create.bats, line 37)
     `assert_success' failed
   REPOSITORY                                 TAG         IMAGE ID      CREATED       SIZE
   registry.fedoraproject.org/fedora-toolbox  35          30e2dd6cf22e  2 weeks ago   346 MB
   registry.fedoraproject.org/fedora-toolbox  32          6b2cbce8102f  3 months ago  371 MB

   -- command failed --
   status : 1
   output : Error: failed to create container fedora32
   --

 ✓ create: Try to create a container with invalid custom name ('ßpeci@l.Nam€'; using positional argument)
 ✓ create: Try to create a container with invalid custom name ('ßpeci@l.Nam€'; using option --container)
 ✗ create: Create a container with a distro and release options ('fedora'; f32)
   (from function `assert_success' in file /usr/share/toolbox/test/system/libs/bats-assert/src/assert.bash, line 114,
    in test file /usr/share/toolbox/test/system/101-create.bats, line 63)
     `assert_success' failed

   -- command failed --
   status : 1
   output : Error: failed to create container fedora-toolbox-32
   --

 ✓ create: Try to create a container based on non-existent image
 ✓ list: Run 'list' with zero containers and zero images (the list should be empty)
 ✓ list: Run 'list -c' with zero containers (the list should be empty)
 ✗ list: Run 'list' with zero toolbox's containers and images, but other image (the list should be empty)
   (from function `assert_success' in file /usr/share/toolbox/test/system/libs/bats-assert/src/assert.bash, line 114,
    from function `pull_distro_image' in file /usr/share/toolbox/test/system/libs/helpers.bash, line 139,
    in test file /usr/share/toolbox/test/system/102-list.bats, line 38)
     `pull_distro_image busybox' failed
   Failed to load image docker.io/library/busybox from cache /tmp/bats-run-17597/image-cache/busybox-toolbox

   -- command failed --
   status : 1
   output (3 lines):
     time="2021-08-02T08:52:22-04:00" level=info msg="Not using native diff for overlay, this may cause degraded performance for building images: opaque flag erroneously copied up, consider update to kernel 4.8 or later to fix"
     time="2021-08-02T08:52:22-04:00" level=fatal msg="Error determining manifest MIME type for dir:/tmp/bats-run-17597/image-cache/busybox-toolbox: open /tmp/bats-run-17597/image-cache/busybox-toolbox/manifest.json: no such file or directory"
     time="2021-08-02T08:52:22-04:00" level=error msg="exit status 1"
   --

 ✗ list: Try to list images and containers (no flag) with 3 containers and 2 images (the list should have 3 images and 2 containers)
   (from function `fail' in file /usr/share/toolbox/test/system/libs/bats-support/src/error.bash, line 40,
    from function `create_default_container' in file /usr/share/toolbox/test/system/libs/helpers.bash, line 198,
    in test file /usr/share/toolbox/test/system/102-list.bats, line 56)
     `create_default_container' failed
   (from function `fail' in file /usr/share/toolbox/test/system/libs/bats-support/src/error.bash, line 40,
    from function `create_default_container' in file /usr/share/toolbox/test/system/libs/helpers.bash, line 198,
    in test file /usr/share/toolbox/test/system/103-container.bats, line 19)
     `create_default_container' failed
   REPOSITORY                                 TAG         IMAGE ID      CREATED      SIZE
   registry.fedoraproject.org/fedora-toolbox  35          30e2dd6cf22e  2 weeks ago  346 MB
   Error: failed to create container fedora-toolbox-35
   Toolbox couldn't create default container
 ✓ run: Try to run echo 'Hello World' with no containers created
 ✗ run: Run echo 'Hello World' inside of the default container
   (from function `fail' in file /usr/share/toolbox/test/system/libs/bats-support/src/error.bash, line 40,
    from function `create_default_container' in file /usr/share/toolbox/test/system/libs/helpers.bash, line 198,
    in test file /usr/share/toolbox/test/system/104-run.bats, line 25)
     `create_default_container' failed
   Error: failed to create container fedora-toolbox-35
   Toolbox couldn't create default container
 ✗ run: Run echo 'Hello World' inside a container after being stopped
   (from function `fail' in file /usr/share/toolbox/test/system/libs/bats-support/src/error.bash, line 40,
    from function `create_distro_container' in file /usr/share/toolbox/test/system/libs/helpers.bash, line 175,
    from function `create_container' in file /usr/share/toolbox/test/system/libs/helpers.bash, line 189,
    in test file /usr/share/toolbox/test/system/104-run.bats, line 34)
     `create_container running' failed
   Error: failed to create container running
   Toolbox couldn't create container 'running'
 ✗ run: Run sudo id inside of the default container
   (from function `fail' in file /usr/share/toolbox/test/system/libs/bats-support/src/error.bash, line 40,
    from function `create_default_container' in file /usr/share/toolbox/test/system/libs/helpers.bash, line 198,
    in test file /usr/share/toolbox/test/system/104-run.bats, line 46)
     `create_default_container' failed
   Error: failed to create container fedora-toolbox-35
   Toolbox couldn't create default container
 ✓ rm: Try to remove a non-existent container
 - rm: Try to remove a running container (skipped: Bug: Fail in 'toolbox rm' does not return non-zero value)
 ✗ rm: Remove a not running container
   (from function `fail' in file /usr/share/toolbox/test/system/libs/bats-support/src/error.bash, line 40,
    from function `create_distro_container' in file /usr/share/toolbox/test/system/libs/helpers.bash, line 175,
    from function `create_container' in file /usr/share/toolbox/test/system/libs/helpers.bash, line 189,
    in test file /usr/share/toolbox/test/system/105-rm.bats, line 36)
     `create_container not-running' failed
   Error: failed to create container not-running
   Toolbox couldn't create container 'not-running'
 ✗ rm: Force remove a running container
   (from function `fail' in file /usr/share/toolbox/test/system/libs/bats-support/src/error.bash, line 40,
    from function `create_distro_container' in file /usr/share/toolbox/test/system/libs/helpers.bash, line 175,
    from function `create_container' in file /usr/share/toolbox/test/system/libs/helpers.bash, line 189,
    in test file /usr/share/toolbox/test/system/105-rm.bats, line 45)
     `create_container running' failed
   Error: failed to create container running
   Toolbox couldn't create container 'running'
 ✗ rm: Force remove all containers (with 2 containers created and 1 running)
   (from function `fail' in file /usr/share/toolbox/test/system/libs/bats-support/src/error.bash, line 40,
    from function `create_distro_container' in file /usr/share/toolbox/test/system/libs/helpers.bash, line 175,
    from function `create_container' in file /usr/share/toolbox/test/system/libs/helpers.bash, line 189,
    in test file /usr/share/toolbox/test/system/105-rm.bats, line 58)
     `create_container running' failed
   Error: failed to create container running
   Toolbox couldn't create container 'running'
 ✓ rmi: Remove all images with the default image present
 - rmi: Try to remove all images with a container present and running (skipped: Bug: Fail in 'toolbox rmi' does not return non-zero value)
 ✗ rmi: Force remove all images with a container present and running
   (from function `fail' in file /usr/share/toolbox/test/system/libs/bats-support/src/error.bash, line 40,
    from function `create_distro_container' in file /usr/share/toolbox/test/system/libs/helpers.bash, line 175,
    from function `create_container' in file /usr/share/toolbox/test/system/libs/helpers.bash, line 189,
    in test file /usr/share/toolbox/test/system/106-rmi.bats, line 54)
     `create_container foo' failed
   REPOSITORY                                 TAG         IMAGE ID      CREATED      SIZE
   registry.fedoraproject.org/fedora-toolbox  35          30e2dd6cf22e  2 weeks ago  346 MB
   Error: failed to create container foo
   Toolbox couldn't create container 'foo'
 ✓ test suite: Teardown

41 tests, 14 failures, 2 skipped
$ rpm -qa|egrep 'toolbox|podman'|sort
podman-3.3.0-0.24.dev.gitd32e566.fc35.x86_64
podman-plugins-3.3.0-0.24.dev.gitd32e566.fc35.x86_64
toolbox-0.0.99.2^2.git40fbd377ed0b-1.fc35.x86_64
toolbox-tests-0.0.99.2^2.git40fbd377ed0b-1.fc35.x86_64
$ uname -r
5.13.0-0.rc7.20210625git44db63d1ad8d.55.fc35.x86_64
```

**Comment by olivergs** [comment]
Ok. our testing environment only differs in the kernel version.

Can you give us the output of

`toolbox create -v`

Thanks

**Comment by edsantiago** [comment]
```console
$ toolbox create -v
DEBU Running as real user ID 1000
DEBU Resolved absolute path to the executable as /usr/bin/toolbox
DEBU Running on a cgroups v2 host
DEBU Checking if /etc/subgid and /etc/subuid have entries for user fedora
DEBU Validating sub-ID file /etc/subuid
DEBU Validating sub-ID file /etc/subgid
DEBU TOOLBOX_PATH is /usr/bin/toolbox
DEBU Migrating to newer Podman
DEBU Toolbox config directory is /home/fedora/.config/toolbox
DEBU Current Podman version is 3.3.0-dev
DEBU Creating runtime directory toolbox
DEBU Old Podman version is 3.3.0-dev
DEBU Migration not needed: Podman version 3.3.0-dev is unchanged
DEBU Setting up configuration
DEBU Setting up configuration: file /home/fedora/.config/containers/toolbox.conf not found
DEBU Resolving image name
DEBU Distribution (CLI): ''
DEBU Image (CLI): ''
DEBU Release (CLI): ''
DEBU Resolved image name
DEBU Image: 'fedora-toolbox:35'
DEBU Release: '35'
DEBU Resolving container name
DEBU Container: ''
DEBU Image: 'fedora-toolbox:35'
DEBU Release: '35'
DEBU Resolved container name
DEBU Container: 'fedora-toolbox-35'
DEBU Resolving image name
DEBU Distribution (CLI): ''
DEBU Image (CLI): ''
DEBU Release (CLI): ''
DEBU Resolved image name
DEBU Image: 'fedora-toolbox:35'
DEBU Release: '35'
DEBU Resolving container name
DEBU Container: ''
DEBU Image: 'fedora-toolbox:35'
DEBU Release: '35'
DEBU Resolved container name
DEBU Container: 'fedora-toolbox-35'
DEBU Checking if container fedora-toolbox-35 already exists
DEBU Looking for image localhost/fedora-toolbox:35
DEBU Resolving fully qualified name for image fedora-toolbox:35 from known registries
DEBU Resolved image fedora-toolbox:35 to registry.fedoraproject.org/fedora-toolbox:35
DEBU Looking for image registry.fedoraproject.org/fedora-toolbox:35
Image required to create toolbox container.
Download registry.fedoraproject.org/fedora-toolbox:35 (500MB)? [y/N]: y
DEBU Pulling image registry.fedoraproject.org/fedora-toolbox:35
Trying to pull registry.fedoraproject.org/fedora-toolbox:35...
Getting image source signatures
Copying blob ed03887c1ee5 done
Copying blob 6a1faf443637 done
Copying config 30e2dd6cf2 done
Writing manifest to image destination
Storing signatures
DEBU Resolving fully qualified name for image fedora-toolbox:35 from RepoTags
DEBU Resolved image fedora-toolbox:35 to registry.fedoraproject.org/fedora-toolbox:35
DEBU Checking if 'podman create' supports '--mount type=devpts'
DEBU 'podman create' supports '--mount type=devpts'
DEBU Checking if 'podman create' supports '--ulimit host'
DEBU 'podman create' supports '--ulimit host'
DEBU Resolving path to the D-Bus system socket
DEBU /home/fedora canonicalized to /home/fedora
DEBU Resolving path to the Avahi socket
DEBU failed to find a SOCK_STREAM socket for avahi-daemon.socket
DEBU Resolving path to the KCM socket
DEBU Checking if /media is a symbolic link to /run/media
DEBU Checking if /mnt is a symbolic link to /var/mnt
DEBU Looking for toolbox.sh
DEBU Found /etc/profile.d/toolbox.sh
DEBU Checking if /home is a symbolic link to /var/home
DEBU Creating container fedora-toolbox-35:
DEBU podman
DEBU --log-level
DEBU error
DEBU create
DEBU --dns
DEBU none
DEBU --env
DEBU TOOLBOX_PATH=/usr/bin/toolbox
DEBU --env
DEBU XDG_RUNTIME_DIR=
DEBU --hostname
DEBU toolbox
DEBU --ipc
DEBU host
DEBU --label
DEBU com.github.containers.toolbox=true
DEBU --label
DEBU com.github.debarshiray.toolbox=true
DEBU --mount
DEBU type=devpts,destination=/dev/pts
DEBU --name
DEBU fedora-toolbox-35
DEBU --network
DEBU host
DEBU --no-hosts
DEBU --pid
DEBU host
DEBU --privileged
DEBU --security-opt
DEBU label=disable
DEBU --ulimit
DEBU host
DEBU --userns
DEBU keep-id
DEBU --user
DEBU root:root
DEBU --volume
DEBU /:/run/host:rslave
DEBU --volume
DEBU /dev:/dev:rslave
DEBU --volume
DEBU /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
DEBU --volume
DEBU /home/fedora:/home/fedora:rslave
DEBU --volume
DEBU /usr/bin/toolbox:/usr/bin/toolbox:ro
DEBU --volume
DEBU :
DEBU --volume
DEBU /run/.heim_org.h5l.kcm-socket:/run/.heim_org.h5l.kcm-socket
DEBU --volume
DEBU /media:/media:rslave
DEBU --volume
DEBU /mnt:/mnt:rslave
DEBU --volume
DEBU /run/media:/run/media:rslave
DEBU --volume
DEBU /etc/profile.d/toolbox.sh:/etc/profile.d/toolbox.sh:ro
DEBU registry.fedoraproject.org/fedora-toolbox:35
DEBU toolbox
DEBU --log-level
DEBU debug
DEBU init-container
DEBU --gid
DEBU 1000
DEBU --home
DEBU /home/fedora
DEBU --shell
DEBU /bin/bash
DEBU --uid
DEBU 1000
DEBU --user
DEBU fedora
DEBU --monitor-host
Error: host directory cannot be empty
Error: failed to create container fedora-toolbox-35
```

**Comment by olivergs** [comment]
Seems that for some reason Toolbox is not able to resolve $XDG_RUNTIME_DIR environment variable.

Could you echo the variable? Usually should throw /run/user/UID, but I suspect in your case is empty.

**Comment by edsantiago** [comment]
Setting `$XDG_RUNTIME_DIR` helps, but not entirely:
```console
$ bats /usr/share/toolbox/test/system/ 2>&1 | ts -s '[%H:%M:%S] '
[00:00:01]  1..41
[00:13:03]  ok 1 test suite: Setup
[00:13:03]  ok 2 version: Check version using option --version
[00:13:05]  ok 3 help: Run command 'help'
[00:13:05]  ok 4 help: Use flag '--help' (it should show usage screen)
[00:13:05]  ok 5 help: Try to run toolbox with non-existent command (shows usage screen)
[00:13:05]  ok 6 help: Try to run toolbox with non-existent flag (shows usage screen)
[00:13:05]  ok 7 help: Try to run 'toolbox create' with non-existent flag (shows usage screen)
[00:13:05]  ok 8 help: Try to run 'toolbox enter' with non-existent flag (shows usage screen)
[00:13:05]  ok 9 help: Try to run 'toolbox help' with non-existent flag (shows usage screen)
[00:13:06]  ok 10 help: Try to run 'toolbox init-container' with non-existent flag (shows usage screen)
[00:13:06]  ok 11 help: Try to run 'toolbox list' with non-existent flag (shows usage screen)
[00:13:06]  ok 12 help: Try to run 'toolbox rm' with non-existent flag (shows usage screen)
[00:13:06]  ok 13 help: Try to run 'toolbox rmi' with non-existent flag (shows usage screen)
[00:13:06]  ok 14 help: Try to run 'toolbox run' with non-existent flag (shows usage screen)
[00:14:42]  ok 15 create: Create the default container
[00:14:52]  ok 16 create: Create a container with a valid custom name ('custom-containerName')
[00:16:37]  ok 17 create: Create a container with a custom image and name ('fedora32'; f32)
[00:16:38]  ok 18 create: Try to create a container with invalid custom name ('ßpeci@l.Nam€'; using positional argument)
[00:16:38]  ok 19 create: Try to create a container with invalid custom name ('ßpeci@l.Nam€'; using option --container)
[00:16:48]  ok 20 create: Create a container with a distro and release options ('fedora'; f32)
[00:16:50]  ok 21 create: Try to create a container based on non-existent image
[00:17:08]  ok 22 list: Run 'list' with zero containers and zero images (the list should be empty)
[00:17:10]  ok 23 list: Run 'list -c' with zero containers (the list should be empty)
[00:17:12]  ok 24 list: Run 'list -i' with zero images (the list should be empty)
[00:17:14]  not ok 25 list: Run 'list' with zero toolbox's containers and images, but other image (the list should be empty)
[00:17:14]  # (from function `assert_success' in file /usr/share/toolbox/test/system/libs/bats-assert/src/assert.bash, line 114,
[00:17:14]  #  from function `pull_distro_image' in file /usr/share/toolbox/test/system/libs/helpers.bash, line 139,
[00:17:14]  #  in test file /usr/share/toolbox/test/system/102-list.bats, line 38)
[00:17:14]  #   `pull_distro_image busybox' failed
[00:17:14]  # Failed to load image docker.io/library/busybox from cache /var/tmp/bats-run-60247/image-cache/busybox-toolbox
[00:17:14]  #
[00:17:14]  # -- command failed --
[00:17:14]  # status : 1
[00:17:14]  # output (2 lines):
[00:17:14]  #   time="2021-08-02T12:24:27-04:00" level=fatal msg="Error determining manifest MIME type for dir:/var/tmp/bats-run-60247/image-cache/busybox-toolbox: open /var/tmp/bats-run-60247/image-cache/busybox-toolbox/manifest.json: no such file or directory"
[00:17:14]  #   time="2021-08-02T12:24:27-04:00" level=error msg="exit status 1"
[00:17:14]  # --
[00:17:14]  #
[00:20:07]  ok 26 list: Try to list images and containers (no flag) with 3 containers and 2 images (the list should have 3 images and 2 containers)
[00:20:10]  ok 27 list: List an image without a name
[00:21:43]  ok 28 container: Check container starts without issues
[00:21:44]  ok 29 run: Try to run echo 'Hello World' with no containers created
[00:21:56]  ok 30 run: Run echo 'Hello World' inside of the default container
[00:22:10]  ok 31 run: Run echo 'Hello World' inside a container after being stopped
[00:22:22]  ok 32 run: Run sudo id inside of the default container
[00:22:23]  ok 33 rm: Try to remove a non-existent container
[00:22:24]  ok 34 rm: Try to remove a running container # skip Bug: Fail in 'toolbox rm' does not return non-zero value
[00:22:34]  ok 35 rm: Remove a not running container
[00:22:45]  ok 36 rm: Force remove a running container
[00:23:06]  ok 37 rm: Force remove all containers (with 2 containers created and 1 running)
[00:23:52]  ok 38 rmi: Remove all images with the default image present
[00:23:53]  ok 39 rmi: Try to remove all images with a container present and running # skip Bug: Fail in 'toolbox rmi' does not return non-zero value
[00:25:48]  ok 40 rmi: Force remove all images with a container present and running
[00:25:49]  ok 41 test suite: Teardown
```
I would encourage you to set a default `$XDG_RUNTIME_DIR` within toolbox itself, as podman does. Not all environments have that defined (e.g. `su - useraccount` from root).

**Comment by olivergs** [comment]
The error in the test 25 seems like a connection error when caching images at (1) setup step.

About the XDG_RUNTIME_DIR We're working to fix it at our side. Seems we are checking for the root user and for normal users cases, but that case you're describing was not implemented. As soon as we fix it I will build a new release for you to test.

**Comment by edsantiago** [comment]
>The error in the test 25 seems like a connection error when caching images at (1) setup step.

I ran tests twice before reporting, once with TMPDIR unset, once with `TMPDIR=/var/tmp`; so whatever the error is, it seems to be consistent. Ping me on IRC (esm @ both Libera and RH internal) if you'd like access to the test VM.

**Comment by olivergs** [comment]
Ok. Let us fix first the XDG_RUNTIME_DIR problem as it has some other things that depend on it and will require some discussion prior to make decisions.

As soon as it is fixed I will do a new release for that and then test it in the machine you are using. Thanks @edsantiago .

**Comment by edsantiago** [comment]
Wait, wouldn't it make sense to look into the not-ok-25 error before making a new release? That failed even with XDG defined.

**Comment by olivergs** [comment]
You're right. I will contact you on IRC later and take a look at that. Thanks for the heads up.

**Comment by olivergs** [comment]
@edsantiago We have fixed the prroblems in the test suite and I've sent a new build to rawhide.

https://koji.fedoraproject.org/koji/taskinfo?taskID=73573768

I suppose it will be available in the next compose. Could you please check it works for you?

**Comment by edsantiago** [comment]
tests pass as user `fedora` on rawhide. Tomorrow I'll look into what it will take to add this to the podman gating tests.

**Comment by edsantiago** [comment]
I have the gating-test fixes necessary to run toolbox-tests as part of podman gating tests in rawhide. They pass using `toolbox-0.0.99.2^3.git075b9a8d2779-1.fc35.x86_64` from the above koji link. 

@containers/podman-maintainers where do we want to go with this? Are we really OK with running these tests as part of our rawhide gating?

**Comment by edsantiago** [comment]
[the diffs](https://src.fedoraproject.org/fork/santiago/rpms/podman/diff/rawhide..add_toolbox_gating). I am not pushing to fedpkg, nor even submitting as a PR, because (1) the `^3` build is not yet in stable, and (2) we need discussion from the podman team.

**Comment by edsantiago** [comment]
@olivergs @HarryMichal I believe we have buy-in to enable this in podman. I just did a final review, and hit a showstopper: as best I can see, you do not have a `gating.yaml` in your [source tree](https://src.fedoraproject.org/rpms/toolbox/tree/rawhide): meaning, you do not have gating tests enabled or running on your package. Please enable gating tests on rawhide. Once we see those enabled and passing, we will proceed on our end.

**Comment by olivergs** [comment]
Hi @edsantiago. Ok. I'll work on that during the week and tell you when ready.

Thanks!

**Comment by edsantiago** [comment]
Hi @olivergs, how goes your effort to set up toolbox gating tests?

Also, are you replicating these tests on f33 and f34? We have a podman release coming soon, and would really welcome feedback from the toolbox team. It's probably too late to integrate gating tests for this release, but if you have a way of running your tests on our bodhi ([f33](https://bodhi.fedoraproject.org/updates/FEDORA-2021-c6e80526ba), [f34](https://bodhi.fedoraproject.org/updates/FEDORA-2021-7ce1dbeb75)) we would be most grateful.

**Comment by olivergs** [comment]
Hi Ed. As we talked about this yesterday, I'm giving the finishing touches to this. The tests are running but them fail. I'm currently trying to get the artifacts for the test to know what is failing. I will give more feedback when this is finished.

**Comment by olivergs** [comment]
Hi again. The gating in fedora is already working for fedora 35. Rawhide fails because there is not a f36 toolbox image yet due to this bug: https://pagure.io/fedora-infrastructure/issue/10145 and f34 needs a backport of https://github.com/containers/toolbox/pull/857 . 

@edsantiago You should be able to check it in f35 right now.

On the other hand, I tested latest podman locally from this build: https://koji.fedoraproject.org/koji/taskinfo?taskID=74625958 and executed the test suite with the latest upstream for toolbox. It passes without major incidents and the usual workflow for toolbox seems ok.

**Comment by edsantiago** [comment]
Submitted [PR for f35](https://src.fedoraproject.org/rpms/podman/pull-request/47). Confirmed that it works in 1minutetip. Also confirmed hat you have an [f35 bodhi](https://bodhi.fedoraproject.org/updates/FEDORA-2021-24762cac24) and that tests pass.

**Comment by edsantiago** [comment]
That PR is now merged. Toolbox gating tests are now enabled for podman on f35. But @containers/podman-maintainers I think we have a problem coming up.

For any given Fedora NN, toolbox seems to want to pull a `toolbox` image with the tag `fNN`. That means that as soon as `fNN` branches from Rawhide and Rawhide becomes `fNN+1`, **podman rawhide bodhi will break** because the toolbox team will not have a tagged image. We are seeing this right now with `f36`; and because of the [bug mentioned above](https://pagure.io/fedora-infrastructure/issue/10145) it may take months to actually get such a tagged image. That would presumably mean months of broken podman bodhis.

I kind of don't think this is acceptable. I would like to ask the toolbox team to make their process more robust, perhaps to pre-tag an `fNN+1` image in advance (even if it's bogus), or to otherwise find a solution to this. But this isn't my call to make, and perhaps I'm making it out to be more serious than it is. I would appreciate further thoughts from @olivergs and/or other knowledgeable parties.

**Comment by travier** [comment]
Toolbox now has support for [basic config files](https://github.com/containers/toolbox/blob/main/data/config/toolbox.conf) that we can use to default to a working image on Rawhide. We of course would need to bump this config from time to time but this rather easy to do.

**Comment by travier** [comment]
And thanks for the work here!

**Comment by debarshiray** [comment]
> podman rawhide bodhi will break because the toolbox team will
> not have a tagged image.

Building a new image is a matter of doing a `fedpkg container-build`. It's pretty trivial, and various people (eg., @juhp) help out with it already. You could do that if you notice that Rawhide gating is missing an image after branching.

> We are seeing this right now with f36;
> and because of the bug mentioned above it may take months to
> actually get such a tagged image. That would presumably mean
> months of broken podman bodhis.

Umm... honest question: what makes you think that it will take *months*? I do see activity on the Fedora infrastructure [ticket](https://pagure.io/fedora-infrastructure/issue/10145).

> I kind of don't think this is acceptable. I would like to ask the
> toolbox team to make their process more robust

I am not sure what the Toolbox developers can do if Fedora's OCI infrastructure is broken, other than talking to the Fedora infra' folks and trying to get it prioritized. Given that this free software and community and all that, anybody else can help convey that message too. :)

**Comment by debarshiray** [comment]
The [issue](https://pagure.io/fedora-infrastructure/issue/10145) with the Fedora infrastructure got fixed, and we have new image builds in place now.

**Comment by edsantiago** [comment]
Thanks! I see gating tests [failing](https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/dist-git-pipeline/job/master/72193/testReport/(root)/tests/toolbox/). Please update here when those are fixed, we will then look into enabling this on podman rawhide.

**Comment by olivergs** [comment]
@edsantiago The image seems to be in stage yet. As soon as it reaches main regisitry we should be able to check.

On the other hand, the infra bug reappeared. I've reopened the issue and asked for fixing it again.

**Comment by juhp** [comment]
fedora-toolbox:36 should in the stable fedora registry now.

**Comment by olivergs** [comment]
Thanks @juhp !. Yes. It is in stable and after re-running the CI, the gating passes.

https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/dist-git-pipeline/job/master/72523/

**Comment by olivergs** [comment]
> @edsantiago The image seems to be in stage yet. As soon as it reaches main regisitry we should be able to check.
> 
> On the other hand, the infra bug reappeared. I've reopened the issue and asked for fixing it again.

The infra bug seemed to be just a node that did not updated correctly. Now seems everything works as expected.

**Comment by edsantiago** [comment]
Do you have a link to a working bodhi? All I see is [toolbox-0.0.99.2^3.git075b9a8d2779-6.fc36](https://bodhi.fedoraproject.org/updates/FEDORA-2021-2329b4f091), which fails. I see the jenkins link you posted, but I don't see that actually being reflected in bodhi.

**Comment by olivergs** [comment]
I've rerun the build because the last time I just run the CI work.

Here you have a bodhi update: https://bodhi.fedoraproject.org/updates/FEDORA-2021-306c96fe51

**Comment by edsantiago** [comment]
Thank you! I've submitted a [PR for rawhide](https://src.fedoraproject.org/rpms/podman/pull-request/48).

**Comment by olivergs** [comment]
Thank you @edsantiago !

**Comment by edsantiago** [comment]
Toolbox gating tests are now [running and passing in rawhide](https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/dist-git-pipeline/job/master/79733/testReport/(root)/tests/) and in f35. Thank you everyone for your perseverance and patience.

**Comment by debarshiray** [comment]
Yay! That's wonderful to hear. Thanks, @edsantiago
