### ISSUE TITLE
Docs: secrets command links 404

### ISSUE THREAD

**Issue by Mossman1215** [containers/podman#10513]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I can't find the documentation for podman-secrets-create command on the first google search result because the links in the upper level documentation don't work

**Steps to reproduce the issue:**

1. browse to http://docs.podman.io/en/latest/Commands.html

2. click the link to [secret](http://docs.podman.io/en/latest/markdown/podman-secret.1.html)

3. click any of the sub command links

![image](https://user-images.githubusercontent.com/3606406/120247525-da332f00-c2c7-11eb-8a23-7c0b4ff5d14d.png)

4. get a maze found page instead of linking to the published link http://docs.podman.io/en/latest/markdown/podman-secret-create.1.html

**Describe the results you received:**
404 errors :cry: 

**Describe the results you expected:**

Unlike the pod command, the pages for secrets have .1.html attached which seems wrong

**Additional information you deem important (e.g. issue happens only occasionally):**

I'm assuming that link.lua is supposed to rename the output to .html but that hasn't worked.

I've run the build process locally and also had the same outputs and 404 page
![Screenshot from 2021-06-01 11-04-54](https://user-images.githubusercontent.com/3606406/120248158-2f704000-c2ca-11eb-84ee-5b6d990477d7.png)

**Comment by Mossman1215** [comment]
Please let me know if there are any further things I can test.

**Comment by vrothberg** [comment]
Thanks for opening the issue!

@baude PTAL

**Comment by zhangguanzhang** [comment]
also exsit in http://docs.podman.io/en/latest/markdown/podman-machine.1.html

**Comment by rhatdan** [comment]
Those should be fixed by the update.

**Comment by vrothberg** [comment]
I just tested, it works now. Thanks!

**Comment by Mossman1215** [comment]
thanks!

**Comment by zhangguanzhang** [comment]
http://docs.podman.io/en/latest/markdown/podman-secret-create.1.md
still happend

**Comment by rhatdan** [comment]
How do you get to that link?

**Comment by rhatdan** [comment]
http://docs.podman.io/en/latest/Commands.html
Click on Secret
Click on Create
Takes me to
http://docs.podman.io/en/latest/markdown/podman-secret-create.1.html

**Comment by zhangguanzhang** [comment]
now , it works

**Comment by rhatdan** [comment]
Awesome, thanks for confirming.
