### ISSUE TITLE
Mirror registry ignored

### ISSUE THREAD

**Issue by maxclac** [containers/podman#14306]
Hello,

I am trying to set up a local mirror of docker.io on Centos 7 with a local registry running on localhost:5000. Let's say I pull an image a first time from docker.io with `podman pull docker.io/busybox`. Now if the mirror is set up correctly, I would expect that, when I remove this image and pull it a second time with the same command, it would be pulled from the local registry at localhost:5000. However, this is not what happens. It keeps pulling from docker.io and nothing happens in my local registry:

```
# curl localhost:5000/v2/_catalog
{"repositories":[]}
```

This is my `/etc/containers/registries.conf` file:
```
[[registry]]
location="docker.io"
[[registry.mirror]]
location="localhost:5000"
insecure=true
```

What would be the problem? 

```
# podman --version
podman version 1.6.4
# podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.12
  podman version: 1.6.4
host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.8-1.el7.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.8, commit: f85c8b1ce77b73bcd48b2d802396321217008762'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 2003165184
  MemTotal: 3973255168
  OCIRuntime:
    name: runc
    package: runc-1.0.0-69.rc10.el7_9.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 2
  eventlogger: journald
  hostname: some-registry
  kernel: 3.10.0-1160.66.1.el7.x86_64
  os: linux
  rootless: false
  uptime: 1h 14m 44.67s (Approximately 0.04 days)
registries:
  blocked: null
  insecure: null
  search: null
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 3
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes

```

**Comment by rhatdan** [comment]
@vrothberg PTAL

**Comment by vrothberg** [comment]
Thanks for reaching out, @maxclac!

To validate the theory, can you share the logs via `podman --log-level=debug pull ...`? If the output indicates that `localhost:5000` is contacted prior to docker.io, then the registry isn't configured correctly.

**Comment by maxclac** [comment]
```
# podman --log-level=debug pull docker.io/busybox
DEBU[0000] Reading configuration file "/usr/share/containers/libpod.conf" 
DEBU[0000] Merged system config "/usr/share/containers/libpod.conf": &{{false false false false false true} 0 {   [] [] []}  docker://  runc map[crun:[/usr/bin/crun /usr/local/bin/crun] runc:[/usr/bin/runc /usr/sbin/runc /usr/local/bin/runc /usr/local/sbin/runc /sbin/runc /bin/runc /usr/lib/cri-o-runc/sbin/runc /run/current-system/sw/bin/runc]] [crun runc] [crun] [] [/usr/libexec/podman/conmon /usr/local/libexec/podman/conmon /usr/local/lib/podman/conmon /usr/bin/conmon /usr/sbin/conmon /usr/local/bin/conmon /usr/local/sbin/conmon /run/current-system/sw/bin/conmon] [PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] systemd   /var/run/libpod -1 false /etc/cni/net.d/ [/usr/libexec/cni /usr/lib/cni /usr/local/lib/cni /opt/cni/bin] podman []   k8s.gcr.io/pause:3.1 /pause false false  2048 shm    false} 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /var/lib/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /var/lib/containers/storage 
DEBU[0000] Using run root /var/run/containers/storage   
DEBU[0000] Using static dir /var/lib/containers/storage/libpod 
DEBU[0000] Using tmp dir /var/run/libpod                
DEBU[0000] Using volume path /var/lib/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] cached value indicated that overlay is supported 
DEBU[0000] cached value indicated that metacopy is not being used 
DEBU[0000] cached value indicated that native-diff is usable 
DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
DEBU[0000] Initializing event backend journald          
DEBU[0000] using runtime "/usr/bin/runc"                
WARN[0000] Error initializing configured OCI runtime crun: no valid executable found for OCI runtime crun: invalid argument 
INFO[0000] Found CNI network podman (type=bridge) at /etc/cni/net.d/87-podman-bridge.conflist 
DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage]docker.io/library/busybox:latest" 
Trying to pull docker.io/busybox...
DEBU[0000] reference rewritten from 'docker.io/library/busybox:latest' to 'localhost:5000/library/busybox:latest' 
DEBU[0000] reference rewritten from 'docker.io/library/busybox:latest' to 'docker.io/library/busybox:latest' 
DEBU[0000] Trying to pull "localhost:5000/library/busybox:latest" 
DEBU[0000] Credentials not found                        
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration 
DEBU[0000]  Using "default-docker" configuration        
DEBU[0000]  No signature storage configuration found for localhost:5000/library/busybox:latest 
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/localhost:5000 
DEBU[0000] GET https://localhost:5000/v2/               
DEBU[0000] Ping https://localhost:5000/v2/ err Get https://localhost:5000/v2/: http: server gave HTTP response to HTTPS client (&url.Error{Op:"Get", URL:"https://localhost:5000/v2/", Err:(*errors.errorString)(0xc000396020)}) 
DEBU[0000] GET http://localhost:5000/v2/                
DEBU[0000] Ping http://localhost:5000/v2/ status 200    
DEBU[0000] GET http://localhost:5000/v2/library/busybox/manifests/latest 
DEBU[0000] Trying to pull "docker.io/library/busybox:latest" 
DEBU[0000] Credentials not found                        
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration 
DEBU[0000]  Using "default-docker" configuration        
DEBU[0000]  No signature storage configuration found for docker.io/library/busybox:latest 
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/docker.io 
DEBU[0000] GET https://registry-1.docker.io/v2/         
DEBU[0000] Ping https://registry-1.docker.io/v2/ status 401 
DEBU[0000] GET https://auth.docker.io/token?scope=repository%3Alibrary%2Fbusybox%3Apull&service=registry.docker.io 
DEBU[0001] GET https://registry-1.docker.io/v2/library/busybox/manifests/latest 
DEBU[0001] Using blob info cache at /var/lib/containers/cache/blob-info-cache-v1.boltdb 
DEBU[0001] Source is a manifest list; copying (only) instance sha256:52f431d980baa76878329b68ddb69cb124c25efa6e206d8b0bd797a828f0528e for current system 
DEBU[0001] GET https://registry-1.docker.io/v2/library/busybox/manifests/sha256:52f431d980baa76878329b68ddb69cb124c25efa6e206d8b0bd797a828f0528e 
DEBU[0002] IsRunningImageAllowed for image docker:docker.io/library/busybox:latest 
DEBU[0002]  Using default policy section                
DEBU[0002]  Requirement 0: allowed                      
DEBU[0002] Overall: allowed                             
DEBU[0002] Downloading /v2/library/busybox/blobs/sha256:1a80408de790c0b1075d0a7e23ff7da78b311f85f36ea10098e4a6184c200964 
DEBU[0002] GET https://registry-1.docker.io/v2/library/busybox/blobs/sha256:1a80408de790c0b1075d0a7e23ff7da78b311f85f36ea10098e4a6184c200964 
Getting image source signatures
DEBU[0002] Manifest has MIME type application/vnd.docker.distribution.manifest.v2+json, ordered candidate list [application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.v1+prettyjws, application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.v1+json] 
DEBU[0002] ... will first try using the original manifest unmodified 
DEBU[0002] Downloading /v2/library/busybox/blobs/sha256:50e8d59317eb665383b2ef4d9434aeaa394dcd6f54b96bb7810fdde583e9c2d1 
DEBU[0002] GET https://registry-1.docker.io/v2/library/busybox/blobs/sha256:50e8d59317eb665383b2ef4d9434aeaa394dcd6f54b96bb7810fdde583e9c2d1 
DEBU[0003] Detected compression format gzip             
DEBU[0003] Using original blob without modification     
Copying blob 50e8d59317eb done
DEBU[0003] No compression detected                      
DEBU[0003] Using original blob without modification     
Copying config 1a80408de7 done
Writing manifest to image destination
Storing signatures
DEBU[0004] Applying tar in /var/lib/containers/storage/overlay/eb6b01329ebe73e209e44a616a0e16c2b8e91de6f719df9c35e6cdadadbe5965/diff 
DEBU[0004] setting image creation date to 2022-04-14 02:29:36.517566461 +0000 UTC 
DEBU[0004] created new image ID "1a80408de790c0b1075d0a7e23ff7da78b311f85f36ea10098e4a6184c200964" 
DEBU[0004] set names of image "1a80408de790c0b1075d0a7e23ff7da78b311f85f36ea10098e4a6184c200964" to [docker.io/library/busybox:latest] 
DEBU[0005] saved image metadata "{\"signatures-sizes\":{\"sha256:52f431d980baa76878329b68ddb69cb124c25efa6e206d8b0bd797a828f0528e\":[]}}" 
DEBU[0005] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage]docker.io/library/busybox:latest" 
1a80408de790c0b1075d0a7e23ff7da78b311f85f36ea10098e4a6184c200964```
```

**Comment by maxclac** [comment]
Thanks @vrothberg ! However, as I posted before, I already set the registry to insecure in my registries.conf.

**Comment by vrothberg** [comment]
Does it work when you set the following?
```
[[registry]]
location="localhost:5000"
insecure=true
```

**Comment by maxclac** [comment]
Yes, even if obviously I can just pull from the local registry.

**Comment by vrothberg** [comment]
I can reproduce the issue on CentOS 7.9 but am unable to find a corresponding bug report since 1.6.4.   It's definitely working in more recent versions of Podman.

Any chance you can upgrade to a newer version?

If you want to see this fixed in 1.6.4, please open a bug in the Red Hat Bugzilla.  Upstream does not support 1.6.4 anymore.

**Comment by maxclac** [comment]
Thanks a lot!

**Comment by rhatdan** [comment]
This is not likely to be back ported BTW,  Best option is to move to RHEL8.

**Comment by maxclac** [comment]
I don't have access to RHEL8. I am trying on Centos 8 Stream with Podman 4.0.2 and it is still not working. Should I open a new ticket?

**Comment by maxclac** [comment]
Hi! I would like to come back to this issue, because I am not sure it is quite solved. The image taken from docker.io is indeed pulled into the local registry but, when I try to pull again, the image is pulled again from docker.io. There is apparently no attempt to look into the local registry first.

**Comment by maxclac** [comment]
I would like to reactivate this issue because it is actually not resolved. Am I the only one trying to do this?

**Comment by vrothberg** [comment]
Sure! Sorry for missing your earlier comment.

Can you share debug logs (and registries.conf) etc. to support your observations?

**Comment by maxclac** [comment]
`registries.conf`:
```conf
unqualified-search-registries = ["docker.io"]

[[registry]]
location = "docker.io"
insecure = true

[[registry.mirror]]
location = "localhost:5000"
insecure = true
short-name-mode = "permissive"

```

Logs:
```bash
# podman --log-level=debug pull --tls-verify=false alpine
INFO[0000] podman filtering at log level debug          
DEBU[0000] Called pull.PersistentPreRunE(podman --log-level=debug pull --tls-verify=false alpine) 
DEBU[0000] Merged system config "/usr/share/containers/containers.conf" 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /var/lib/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /var/lib/containers/storage 
DEBU[0000] Using run root /run/containers/storage       
DEBU[0000] Using static dir /var/lib/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/libpod                    
DEBU[0000] Using volume path /var/lib/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that metacopy is being used 
DEBU[0000] Cached value indicated that native-diff is not being used 
INFO[0000] Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled 
DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=false, usingMetacopy=true 
DEBU[0000] Initializing event backend file              
DEBU[0000] Configured OCI runtime crun initialization failed: no valid executable found for OCI runtime crun: invalid argument 
DEBU[0000] Configured OCI runtime runj initialization failed: no valid executable found for OCI runtime runj: invalid argument 
DEBU[0000] Configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] Configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument 
DEBU[0000] Configured OCI runtime krun initialization failed: no valid executable found for OCI runtime krun: invalid argument 
DEBU[0000] Using OCI runtime "/usr/bin/runc"            
INFO[0000] Setting parallel job count to 13             
DEBU[0000] Pulling image alpine (policy: always)        
DEBU[0000] Looking up image "alpine" in local containers storage 
DEBU[0000] Normalized platform linux/amd64 to {amd64 linux  [] } 
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf" 
DEBU[0000] Failed to decode keys ["registry.mirror.short-name-mode"] from "/etc/containers/registries.conf" 
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf.d/000-shortnames.conf" 
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf.d/001-rhel-shortnames.conf" 
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf.d/002-rhel-shortnames-overrides.conf" 
DEBU[0000] Trying "docker.io/library/alpine:latest" ... 
DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/run/containers/storage:overlay.mountopt=nodev,metacopy=on]@9ed4aefc74f6792b5a804d1d146fe4b4a2299147b0f50eaf2b08435d7b38c27e" 
DEBU[0000] Found image "alpine" as "docker.io/library/alpine:latest" in local containers storage 
DEBU[0000] Found image "alpine" as "docker.io/library/alpine:latest" in local containers storage ([overlay@/var/lib/containers/storage+/run/containers/storage:overlay.mountopt=nodev,metacopy=on]@9ed4aefc74f6792b5a804d1d146fe4b4a2299147b0f50eaf2b08435d7b38c27e) 
DEBU[0000] exporting opaque data as blob "sha256:9ed4aefc74f6792b5a804d1d146fe4b4a2299147b0f50eaf2b08435d7b38c27e" 
DEBU[0000] Image alpine resolved to local image docker.io/library/alpine:latest which will be used for pulling 
DEBU[0000] Normalized platform linux/amd64 to {amd64 linux  [] } 
DEBU[0000] Attempting to pull candidate docker.io/library/alpine:latest for docker.io/library/alpine:latest 
DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/run/containers/storage:overlay.mountopt=nodev,metacopy=on]docker.io/library/alpine:latest" 
Trying to pull docker.io/library/alpine:latest...
DEBU[0000] Copying source image //alpine:latest to destination image [overlay@/var/lib/containers/storage+/run/containers/storage:overlay.mountopt=nodev,metacopy=on]docker.io/library/alpine:latest 
DEBU[0000] Using registries.d directory /etc/containers/registries.d 
DEBU[0000] Trying to access "localhost:5000/library/alpine:latest" 
DEBU[0000] No credentials matching localhost:5000/library/alpine found in /run/user/0/containers/auth.json 
DEBU[0000] No credentials matching localhost:5000/library/alpine found in /root/.config/containers/auth.json 
DEBU[0000] No credentials matching localhost:5000/library/alpine found in /root/.docker/config.json 
DEBU[0000] No credentials matching localhost:5000/library/alpine found in /root/.dockercfg 
DEBU[0000] No credentials for localhost:5000/library/alpine found 
DEBU[0000]  No signature storage configuration found for localhost:5000/library/alpine:latest, using built-in default file:///var/lib/containers/sigstore 
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/localhost:5000 
DEBU[0000] GET https://localhost:5000/v2/               
DEBU[0000] Ping https://localhost:5000/v2/ err Get "https://localhost:5000/v2/": http: server gave HTTP response to HTTPS client (&url.Error{Op:"Get", URL:"https://localhost:5000/v2/", Err:(*errors.errorString)(0xc0001ba8f0)}) 
DEBU[0000] GET http://localhost:5000/v2/                
DEBU[0000] Ping http://localhost:5000/v2/ status 200    
DEBU[0000] GET http://localhost:5000/v2/library/alpine/manifests/latest 
DEBU[0000] Content-Type from manifest GET is "application/json; charset=utf-8" 
DEBU[0000] Accessing "localhost:5000/library/alpine:latest" failed: reading manifest latest in localhost:5000/library/alpine: manifest unknown: manifest unknown 
DEBU[0000] Trying to access "docker.io/library/alpine:latest" 
DEBU[0000] No credentials matching docker.io/library/alpine found in /run/user/0/containers/auth.json 
DEBU[0000] No credentials matching docker.io/library/alpine found in /root/.config/containers/auth.json 
DEBU[0000] No credentials matching docker.io/library/alpine found in /root/.docker/config.json 
DEBU[0000] No credentials matching docker.io/library/alpine found in /root/.dockercfg 
DEBU[0000] No credentials for docker.io/library/alpine found 
DEBU[0000]  No signature storage configuration found for docker.io/library/alpine:latest, using built-in default file:///var/lib/containers/sigstore 
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/docker.io 
DEBU[0000] GET https://registry-1.docker.io/v2/         
DEBU[0000] Ping https://registry-1.docker.io/v2/ status 401 
DEBU[0000] GET https://auth.docker.io/token?scope=repository%3Alibrary%2Falpine%3Apull&service=registry.docker.io 
DEBU[0000] GET https://registry-1.docker.io/v2/library/alpine/manifests/latest 
DEBU[0001] Content-Type from manifest GET is "application/vnd.docker.distribution.manifest.list.v2+json" 
DEBU[0001] Using blob info cache at /var/lib/containers/cache/blob-info-cache-v1.boltdb 
DEBU[0001] Source is a manifest list; copying (only) instance sha256:b6ca290b6b4cdcca5b3db3ffa338ee0285c11744b4a6abaa9627746ee3291d8d for current system 
DEBU[0001] GET https://registry-1.docker.io/v2/library/alpine/manifests/sha256:b6ca290b6b4cdcca5b3db3ffa338ee0285c11744b4a6abaa9627746ee3291d8d 
DEBU[0001] Content-Type from manifest GET is "application/vnd.docker.distribution.manifest.v2+json" 
DEBU[0001] IsRunningImageAllowed for image docker:docker.io/library/alpine:latest 
DEBU[0001]  Using default policy section                
DEBU[0001]  Requirement 0: allowed                      
DEBU[0001] Overall: allowed                             
DEBU[0001] Downloading /v2/library/alpine/blobs/sha256:9ed4aefc74f6792b5a804d1d146fe4b4a2299147b0f50eaf2b08435d7b38c27e 
DEBU[0001] GET https://registry-1.docker.io/v2/library/alpine/blobs/sha256:9ed4aefc74f6792b5a804d1d146fe4b4a2299147b0f50eaf2b08435d7b38c27e 
Getting image source signatures
DEBU[0001] Reading /var/lib/containers/sigstore/library/alpine@sha256=b6ca290b6b4cdcca5b3db3ffa338ee0285c11744b4a6abaa9627746ee3291d8d/signature-1 
DEBU[0001] Not looking for sigstore attachments: disabled by configuration 
DEBU[0001] Manifest has MIME type application/vnd.docker.distribution.manifest.v2+json, ordered candidate list [application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.v1+prettyjws, application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.v1+json] 
DEBU[0001] ... will first try using the original manifest unmodified 
DEBU[0001] Checking if we can reuse blob sha256:f56be85fc22e46face30e2c3de3f7fe7c15f8fd7c4e5add29d7f64b87abdaa09: general substitution = true, compression for MIME type "application/vnd.docker.image.rootfs.diff.tar.gzip" = true 
DEBU[0001] Skipping blob sha256:f56be85fc22e46face30e2c3de3f7fe7c15f8fd7c4e5add29d7f64b87abdaa09 (already present): 
Copying blob f56be85fc22e skipped: already exists  
DEBU[0001] No compression detected                      
DEBU[0001] Compression change for blob sha256:9ed4aefc74f6792b5a804d1d146fe4b4a2299147b0f50eaf2b08435d7b38c27e ("application/vnd.docker.container.image.v1+json") not supported 
DEBU[0001] Using original blob without modification     
Copying config 9ed4aefc74 done  
Writing manifest to image destination
Storing signatures
DEBU[0002] setting image creation date to 2023-03-29 18:19:24.45578926 +0000 UTC 
DEBU[0002] reusing image ID "9ed4aefc74f6792b5a804d1d146fe4b4a2299147b0f50eaf2b08435d7b38c27e" 
DEBU[0002] saved image metadata "{\"signatures-sizes\":{\"sha256:b6ca290b6b4cdcca5b3db3ffa338ee0285c11744b4a6abaa9627746ee3291d8d\":[]}}" 
DEBU[0002] added name "docker.io/library/alpine:latest" to image "9ed4aefc74f6792b5a804d1d146fe4b4a2299147b0f50eaf2b08435d7b38c27e" 
DEBU[0002] Pulled candidate docker.io/library/alpine:latest successfully 
DEBU[0002] Looking up image "9ed4aefc74f6792b5a804d1d146fe4b4a2299147b0f50eaf2b08435d7b38c27e" in local containers storage 
DEBU[0002] Trying "9ed4aefc74f6792b5a804d1d146fe4b4a2299147b0f50eaf2b08435d7b38c27e" ... 
DEBU[0002] parsed reference into "[overlay@/var/lib/containers/storage+/run/containers/storage:overlay.mountopt=nodev,metacopy=on]@9ed4aefc74f6792b5a804d1d146fe4b4a2299147b0f50eaf2b08435d7b38c27e" 
DEBU[0002] Found image "9ed4aefc74f6792b5a804d1d146fe4b4a2299147b0f50eaf2b08435d7b38c27e" as "9ed4aefc74f6792b5a804d1d146fe4b4a2299147b0f50eaf2b08435d7b38c27e" in local containers storage 
DEBU[0002] Found image "9ed4aefc74f6792b5a804d1d146fe4b4a2299147b0f50eaf2b08435d7b38c27e" as "9ed4aefc74f6792b5a804d1d146fe4b4a2299147b0f50eaf2b08435d7b38c27e" in local containers storage ([overlay@/var/lib/containers/storage+/run/containers/storage:overlay.mountopt=nodev,metacopy=on]@9ed4aefc74f6792b5a804d1d146fe4b4a2299147b0f50eaf2b08435d7b38c27e) 
DEBU[0002] exporting opaque data as blob "sha256:9ed4aefc74f6792b5a804d1d146fe4b4a2299147b0f50eaf2b08435d7b38c27e" 
9ed4aefc74f6792b5a804d1d146fe4b4a2299147b0f50eaf2b08435d7b38c27e
DEBU[0002] Called pull.PersistentPostRunE(podman --log-level=debug pull --tls-verify=false alpine)
```

What I am expecting is that, after the first pull, the image appears in my local registry, for example when I do `curl localhost:5000/v2/_catalog`.

**Comment by maxclac** [comment]
No idea anyone?

**Comment by vrothberg** [comment]
Sorry for not going back to you earlier, @maxclac.

Your config is invalid, see
> DEBU[0000] Failed to decode keys ["registry.mirror.short-name-mode"] from "/etc/containers/registries.conf" 

The `short-name-mode` will be interpreted as an attribute of a `registry.mirror`.  It's just/unfortunately how TOML works.  Moving it up as shown below should fix your issue:
```TOML
unqualified-search-registries = ["docker.io"]
short-name-mode = "permissive"               
                                             
[[registry]]                                 
location = "docker.io"                       
insecure = true                              
                                             
[[registry.mirror]]                          
location = "localhost:5000"                  
insecure = true                              
```

**Comment by vrothberg** [comment]
The reason for not erroring out is forward/backward compatibility.  If we add a new field to `registries.conf` and not all clients are updated at the same time, we want old clients to continue work and not error out with "I do not know 'new_field'".  A error log would be equally annoying, so we opted for a debug log.

**Comment by maxclac** [comment]
Thank you. This is still not working.

Could the following error message indicate what is wrong?
```
DEBU[0000] Ping https://localhost:5000/v2/ err Get "https://localhost:5000/v2/": http: server gave HTTP response to HTTPS client (&url.Error{Op:"Get", URL:"https://localhost:5000/v2/", Err:(*errors.errorString)(0xc000433460)}) 
```

**Comment by vrothberg** [comment]
Podman will always try `https` first.  With `insecure=true` it will fallback to using `http`, so you should see something like below in your logs:
```
DEBU[0000] GET https://localhost:5000/v2/                                                                                                                                                                                         
DEBU[0000] Ping https://localhost:5000/v2/ err Get "https://localhost:5000/v2/": http: server gave HTTP response to HTTPS client (&url.Error{Op:"Get", URL:"https://localhost:5000/v2/", Err:(*errors.errorString)(0xc00044f990)})
DEBU[0000] GET http://localhost:5000/v2/                                                                                                                                                                                          
DEBU[0000] Ping http://localhost:5000/v2/ status 200                                                                                                                                                                              
```

**Comment by maxclac** [comment]
Yes, that's right. Something else is wrong, then.

**Comment by vrothberg** [comment]
Can you share what makes you deduce it doesn't work?  Happy to help debug.

**Comment by maxclac** [comment]
What I expect from a mirror registry is, when I first pull an image from docker.io, it is automatically pushed to the mirror registry. When I subsequently do `podman pull`, it should pull from the local mirror registry. In my case, this is not happening and `podman pull` always pulls from docker.io.

**Comment by vrothberg** [comment]
If you see in the debug logs Podman contacting the mirror fist, Podman works as expected.  Whether the image is on the specified mirror is really up to this mirror.  Podman won't push the image to mirror.

But you will get the desired behavior by configuring the mirror to act as a pull-through cache.  The following command, for instance, configures the `registry:2` mirror to act as pull-through cache for quay.io:
`podman run -d -p 5000:5000 -e REGISTRY_PROXY_REMOTEURL="https://quay.io" registry:2`

**Comment by maxclac** [comment]
It's still not working. Do I need to change `registries.conf`?

**Comment by maxclac** [comment]
Also, I cannot find any documentation online about mirrors acting as a pull-through cache with Podman. Is it such a rare use case?

**Comment by vrothberg** [comment]
> It's still not working. Do I need to change `registries.conf`?

You need to configure `registries.conf` like that:
```TOML
[[registry]]                                 
location = "docker.io"                                                   
                                             
[[registry.mirror]]                          
location = "localhost:5000"                  
insecure = true  
```

And run the mirror like that: `podman run -d -p 5000:5000 -e REGISTRY_PROXY_REMOTEURL="https://quay.io" registry:2`

> Also, I cannot find any documentation online about mirrors acting as a pull-through cache with Podman. Is it such a rare use case?

I think you had a specific expectation of Podman and mirrors.  As mentioned above, Podman will not push to a mirror but only pull from it.  `man containers-registries.conf` goes into the details of the behavior (i.e., trying the mirrors in the specified order and as a last attempt the main registry).

When it comes to the behavior of `registry:2`, that is outside the control of Podman.  The details about that are a bit hidden (see https://docs.docker.com/registry/recipes/mirror/#run-a-registry-as-a-pull-through-cache).

But I'll take your feedback seriously and will sit down to write a blog post about this very example.

**Comment by maxclac** [comment]
Thank you for this! Something is a bit strange: in `registries.conf`, the main registry is `docker.io`, but in your podman command, you use `quay.io` as proxy. Is it on purpose? Should this not be all `docker.io`?

I tried again with what you suggested and it is still not working.

**Comment by vrothberg** [comment]
Apologies, yes, for it to act as a pull-through cache for Docker Hub, you need to configure it to `https://registry-1.docker.io` (see https://docs.docker.com/registry/recipes/mirror/#run-a-registry-as-a-pull-through-cache).

**Comment by maxclac** [comment]
Now it works! Thank you so much @vrothberg !
