### ISSUE TITLE
go test -race trips data race detector in `system.Events`

### ISSUE THREAD

**Issue by thediveo** [containers/podman#15657]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Enabling Go's race detector on unit tests that make use of `system.Event` reports a data race; as the particular code parts seem to be unchanged between v3 and v4 major sem versions, I'm reporting here based on the v3 code base, as this is what I have to work with in order to build podman REST API clients that function on long-term stable distributions, such as Debian 11 and Ubuntu 22.04 which ship the podman v3 binary.

Anyway, the data race condition shown below relates to an `err` variable which seems to not have been properly recreated in a go-routine's local scope; links are in current v4 main branch:

https://github.com/containers/podman/blob/2f555c0c74d77e4a93ef90290f16d0908829e8c7/pkg/bindings/system/system.go#L39

versus

https://github.com/containers/podman/blob/2f555c0c74d77e4a93ef90290f16d0908829e8c7/pkg/bindings/system/system.go#L47

Could this be a "colon incident", a case of `=` when `:=` was meant in line 39?

**Steps to reproduce the issue:**

1. clone https://github.com/thediveo/sealwatcher -- this uses podman's `system.Events`

2. go test -v -exec sudo -p=1 -race ./...

**Describe the results you received:**

In the repo https://github/thediveo/sealwatcher run the unit tests with the race detector enabled:

```
go test -v -exec sudo -p=1 -race ./...
==================
WARNING: DATA RACE
Write at 0x00c0003dc170 by goroutine 46:
  github.com/containers/podman/v3/pkg/bindings/system.Events()
      /home/harald/go/pkg/mod/github.com/containers/podman/v3@v3.4.7/pkg/bindings/system/system.go:47 +0x784
  github.com/thediveo/sealwatcher/podman.(*PodmanWatcher).LifecycleEvents.func1.1()
      /home/harald/github/sealwatcher/podman/podman.go:268 +0x158

Previous write at 0x00c0003dc170 by goroutine 53:
  github.com/containers/podman/v3/pkg/bindings/system.Events.func1()
      /home/harald/go/pkg/mod/github.com/containers/podman/v3@v3.4.7/pkg/bindings/system/system.go:39 +0x96

Goroutine 46 (running) created at:
  github.com/thediveo/sealwatcher/podman.(*PodmanWatcher).LifecycleEvents.func1()
      /home/harald/github/sealwatcher/podman/podman.go:260 +0x655

Goroutine 53 (running) created at:
  github.com/containers/podman/v3/pkg/bindings/system.Events()
      /home/harald/go/pkg/mod/github.com/containers/podman/v3@v3.4.7/pkg/bindings/system/system.go:37 +0x439
  github.com/thediveo/sealwatcher/podman.(*PodmanWatcher).LifecycleEvents.func1.1()
      /home/harald/github/sealwatcher/podman/podman.go:268 +0x158
==================
```

**Describe the results you expected:**

No data races should be detected.

**Comment by Luap99** [comment]
Did you check with the latest code from the podman main branch? I believe I fixed this already in https://github.com/containers/podman/pull/14984 which is not in v4.2.0

**Comment by thediveo** [comment]
The links above are to main branch at the time I wrote the issue report; checking #14984 I don't see that touching the code at all that trips the race detector; we're not talking about a memory leak, but a data race. As I wrote above I carefully checked for the offending code to be still the same on master compared to 3.4.x that tripped my unit tests.

**Comment by Luap99** [comment]
I see, can you open a PR to fix this? Note that we only backport fixes to the latest minor version which is v4.2 at the moment.

**Comment by thediveo** [comment]
Fixed.
