### ISSUE TITLE
Running docker compose leads to docker socket unvailable and WSL stuck

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman#20379]
### Issue Description

On my Windows laptop, I ran `docker compose up` (forget to set DOCKER_BUILDKIT=0) on https://github.com/docker/awesome-compose/tree/master/nginx-golang-postgres

After a while, compose seems to be stuck on :  => => sending tarball

The only container running (docker.io/moby/buildkit:buildx-stable-1) has the following log:
```

time="2023-10-17T07:36:30Z" level=info msg="auto snapshotter: using overlayfs"
time="2023-10-17T07:36:30Z" level=warning msg="using host network as the default"
time="2023-10-17T07:36:30Z" level=info msg="found worker \"tmz81n0vbj5n2unpohhw1dyhk\", labels=map[org.mobyproject.buildkit.worker.executor:oci org.mobyproject.buildkit.worker.hostname:e64f09d4e167 org.mobyproject.buildkit.worker.network:host org.mobyproject.buildkit.worker.oci.process-mode:sandbox org.mobyproject.buildkit.worker.selinux.enabled:false org.mobyproject.buildkit.worker.snapshotter:overlayfs], platforms=[linux/amd64 linux/amd64/v2 linux/amd64/v3 linux/386]"
time="2023-10-17T07:36:30Z" level=warning msg="skipping containerd worker, as \"/run/containerd/containerd.sock\" does not exist"
time="2023-10-17T07:36:30Z" level=info msg="found 1 workers, default=\"tmz81n0vbj5n2unpohhw1dyhk\""
time="2023-10-17T07:36:30Z" level=warning msg="currently, only the default worker can be used."
time="2023-10-17T07:36:30Z" level=info msg="running server on /run/buildkit/buildkitd.sock"
time="2023-10-17T07:37:36Z" level=error msg="/moby.buildkit.v1.Control/Solve returned error: rpc error: code = Canceled desc = failed to copy to tar: rpc error: code = Canceled desc = grpc: the client connection is closing"
```

Once this state is reached, the Docker socket for the Podman machine is not available anymore and it seems WSL is quite stuck: after I Ctrl+C the compose process and stop and rmed the container, restart of the podman machine gives:
```

Starting machine "podman-machine-default"
API forwarding for Docker API clients is not available due to the following startup failures.
        CreateFile \\.\pipe\docker_engine: Toutes les instances des canaux de communication sont occupées.

Podman clients are still able to connect.
Machine "podman-machine-default" started successfully
```

and if I try `wsl --shutdown` after the machine has been stopped, it seems to be stuck and never returns

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman init --rootful --now
2. docker compose up

### Describe the results you received

WSL seems to be stuck and Docker socket is lost

### Describe the results you expected

Should not get WSL to be stuck

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Win11Pro

```
wsl -v

Version WSL : 1.2.5.0
Version du noyau : 5.15.90.1
Version WSLg : 1.0.51
Version MSRDC : 1.2.3770
Version direct3D : 1.608.2-61064218
Version de DXCore : 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Version de Windows : 10.0.22621.2428
```

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by baude** [comment]
@n1hility any ideas on what might be going on?

**Comment by n1hility** [comment]
Looking into this one. 

/assign

**Comment by n1hility** [comment]
I found some time to dig into this further, and the underlying issue is a problem with WSL networking[1]. I tracked down the root implementation cause and have opened an issue with analysis and suggestions on how to fix. I will continue to discuss with them. We could bypass their relay and use a direct connection to the host, but it would only address container control communication, port publishing from the container (e.g. run -p XXXX) would still be susceptible. First I want to see if they plan to take this up soon. It's severe enough they might prioritize it, and waiting for the fix would be the best solution. If not I will post a patch for the partial workaround. 

[1] https://github.com/microsoft/WSL/issues/10688

**Comment by blubberdiblub** [comment]
FWIW, if this is caused by the WSL networking stuff, this is likely also responsible for the infinite hangs I see on some `podman pull` for some images (apparently bigger ones with a higher number of layers, which would support the hypothesis; e.g. try the `python:*` images).

**Comment by Luap99** [comment]
Can we close this one given the bug seems to be in WSL and not podman?

**Comment by Fydon** [comment]
Keeping it open would enable people to more easily find it rather than opening a new issue. I'm barely able to use podman on Windows at the moment with this problem, so maybe there will be more like me.

**Comment by Luap99** [comment]
> Keeping it open would enable people to more easily find it rather than opening a new issue. I'm barely able to use podman on Windows at the moment with this problem, so maybe there will be more like me.

Yes agreed given it seems to affect more people

**Comment by Fydon** [comment]
Given that using [mirrorred networking mode](https://learn.microsoft.com/en-us/windows/wsl/wsl-config) is a[ suggested workaround](https://github.com/microsoft/WSL/issues/10688#issuecomment-2108568123) for the problem we are experiencing, does that impact multi-architecture builds?

My builder on Windows 11 using x64 is now only showing amd64 when I think it used to show arm64 as an option (or at least it did with Docker Desktop). Build with `--platform linux/arm64` are still running, but `docker run` with `--platform linux/arm64` errors with ``exec container process `/bin/bash`: Exec format error``.
```
> docker builder ls
NAME/NODE        DRIVER/ENDPOINT                      STATUS     BUILDKIT   PLATFORMS
mybuilder*       docker-container
 \_ mybuilder0    \_ npipe:////./pipe/docker_engine   running    v0.13.1    linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/386
default          docker-container
 \_ default       \_ default                          inactive
desktop-linux                                         error
```

**Comment by Varriount** [comment]
@Fydon I actually tried enabling mirrored networking as a workaround, and found that it caused Podman/Docker Compose to stop working. Were you able to get it to work?

**Comment by Fydon** [comment]
I'm able to load images, which I wasn't able to with NAT networking. However I'm not able to run the ARM64 images I'm trying to test, as stated above, even if I switch back to NAT networking.

**Comment by POnakS** [comment]
Does podman in mirrored networking work for you? What .wslconfig are you using?

On my machine it throws erros, and docker compose says that it cannot connect to docker socket

**Comment by POnakS** [comment]
Btw this happens only when containers are built as part of docker-compose, otherwise it works.

**Comment by POnakS** [comment]
> Does podman in mirrored networking work for you? What .wslconfig are you using?
> 
> On my machine it throws erros, and docker compose says that it cannot connect to docker socket

After upgrade to docker 5.1 compose starts build but then becomes stuck again on sending tarball (in mirrored mode).

**Comment by POnakS** [comment]
Workaround with mirrored mode does not work for me due ot this:
https://github.com/containers/podman/issues/22975

**Comment by Fydon** [comment]
I see with Podman version 5.1.2 that no longer leads to docker socket becoming unvailable and WSL being when exporting images and instead fails after a short period, which is better:

```
 => ERROR exporting to docker image format                                                                   23.6s 
 => => exporting layers                                                                                      23.5s 
 => => exporting manifest sha256:9be2485ea3d100a0f45db0aa85e8cc1f106123261fc8d4d8ecca3c7a22602ff9            0.0s 
 => => exporting config sha256:ce465544cdca9147515410aaf735a1067246a4d0f98aaa0534be55997e0f6c11              0.0s 
 => => sending tarball                                                                                       0.0s 
------
 > exporting to docker image format:
------
ERROR: failed to solve: failed to copy to tar: rpc error: code = Unknown desc = io: read/write on closed pipe

View build details: docker-desktop://dashboard/build/foo/foo0/gx2ckyaj3uvfq5uu8kp8xobyk
```

It will also immediately fail if the same command is run again. WSL continues to function and other podman/docker commands can will work as long as they don't result in exporting images.

**Comment by ibmmi** [comment]
I have a similar problem while trying to spin a devcontainer.
If I go manually into the devcontainer folder and issue `podman build -t aa .` It finishes well and the image is built.
If I am issuing a "reopen in container" command, then click on show log, I can observe

![Image](https://github.com/user-attachments/assets/2a8278dd-0d48-4fe0-b771-64b4c614cbac)

It gets stuck at "sending tarball" point.

Podman Desktop shows a stuck container:

![Image](https://github.com/user-attachments/assets/8bf513dc-5a1f-4344-966a-cace05d404c3)

Logs from the container are:

```
time="2025-03-13T17:38:39Z" level=info msg="auto snapshotter: using overlayfs"
�time="2025-03-13T17:38:39Z" level=warning msg="CDI setup error /etc/buildkit/cdi: failed to monitor for changes: no such file or directory"
�time="2025-03-13T17:38:39Z" level=warning msg="CDI setup error /etc/cdi: failed to monitor for changes: no such file or directory"
�time="2025-03-13T17:38:39Z" level=warning msg="CDI setup error /var/run/cdi: failed to monitor for changes: no such file or directory"
time="2025-03-13T17:38:39Z" level=warning msg="using host network as the default"
�time="2025-03-13T17:38:39Z" level=info msg="found worker \"vzpymvv2d7leafmgqrrnamjhn\", labels=map[org.mobyproject.buildkit.worker.executor:oci org.mobyproject.buildkit.worker.hostname:aee272f4fadc org.mobyproject.buildkit.worker.network:host org.mobyproject.buildkit.worker.oci.process-mode:sandbox org.mobyproject.buildkit.worker.selinux.enabled:false org.mobyproject.buildkit.worker.snapshotter:overlayfs], platforms=[linux/amd64 linux/amd64/v2 linux/amd64/v3 linux/amd64/v4 linux/386]"
�time="2025-03-13T17:38:39Z" level=warning msg="skipping containerd worker, as \"/run/containerd/containerd.sock\" does not exist"
time="2025-03-13T17:38:39Z" level=info msg="found 1 workers, default=\"vzpymvv2d7leafmgqrrnamjhn\""
time="2025-03-13T17:38:39Z" level=warning msg="currently, only the default worker can be used."
time="2025-03-13T17:38:39Z" level=info msg="running server on /run/buildkit/buildkitd.sock"
time="2025-03-13T17:50:48Z" level=info msg="auto snapshotter: using overlayfs"
�time="2025-03-13T17:50:48Z" level=warning msg="CDI setup error /var/run/cdi: failed to monitor for changes: no such file or directory"
�time="2025-03-13T17:50:48Z" level=warning msg="CDI setup error /etc/buildkit/cdi: failed to monitor for changes: no such file or directory"
�time="2025-03-13T17:50:48Z" level=warning msg="CDI setup error /etc/cdi: failed to monitor for changes: no such file or directory"
time="2025-03-13T17:50:48Z" level=warning msg="using host network as the default"
�time="2025-03-13T17:50:48Z" level=info msg="found worker \"vzpymvv2d7leafmgqrrnamjhn\", labels=map[org.mobyproject.buildkit.worker.executor:oci org.mobyproject.buildkit.worker.hostname:aee272f4fadc org.mobyproject.buildkit.worker.network:host org.mobyproject.buildkit.worker.oci.process-mode:sandbox org.mobyproject.buildkit.worker.selinux.enabled:false org.mobyproject.buildkit.worker.snapshotter:overlayfs], platforms=[linux/amd64 linux/amd64/v2 linux/amd64/v3 linux/amd64/v4 linux/386]"
�time="2025-03-13T17:50:48Z" level=warning msg="skipping containerd worker, as \"/run/containerd/containerd.sock\" does not exist"
time="2025-03-13T17:50:48Z" level=info msg="found 1 workers, default=\"vzpymvv2d7leafmgqrrnamjhn\""
time="2025-03-13T17:50:48Z" level=warning msg="currently, only the default worker can be used."
time="2025-03-13T17:50:48Z" level=info msg="running server on /run/buildkit/buildkitd.sock"
```

Killing the container obtains the effect described above. I need to kill the wsl VM and restart it. After this, the logs on the podman machine seen by podman desktop are>

```
Starting machine "podman-machine-default"
your 131072x1 screen size is bogus. expect trouble
API forwarding for Docker API clients is not available due to the following startup failures.
        CreateFile \\.\pipe\docker_engine: All pipe instances are busy.
Podman clients are still able to connect.
Error: machine did not transition into running state: ssh error: machine not in running state
Starting machine "podman-machine-default"25
your 131072x1 screen size is bogus. expect trouble
API forwarding listening on: npipe:////./pipe/docker_engine
Docker API clients default to this address. You do not need to set DOCKER_HOST.
Machine "podman-machine-default" started successfully
```

Tried it multiple times, the issue is repeatable.
I shut down the podman VM from podman desktop and started Rancher Desktop. It is configured with moby as engine and works perfectly in this situation. I would thus consider that WSL or "networking" related issues are not at fault here...

**Comment by Fydon** [comment]
@timgilbert Does it work with `podman compose build`? With that you may not need `networkingMode=mirrored`.

**Comment by amirkhonov** [comment]
Resolved by uninstalling the entire podman.

**Comment by SimonKuldinMecca** [comment]
is there still no work around to get past the "sending tarball" if using Podman?

**Comment by egwspiti** [comment]
`networkingMode=mirrored` is supported only on windows 11.

**Comment by Fydon** [comment]
For those still experiencing the issue, please try the following. For me
* Podman is running on `podman-machine-default` and is the default
* Podman's API is listening on `npipe:////./pipe/docker_engine`

```
> wsl --list --verbose

  NAME                      STATE           VERSION
* podman-machine-default    Running         2

> podman machine stop podman-machine-default

Machine "podman-machine-default" stopped successfully

> podman machine start podman-machine-default

Starting machine "podman-machine-default"
API forwarding listening on: npipe:////./pipe/docker_engine

Docker API clients default to this address. You do not need to set DOCKER_HOST.
Machine "podman-machine-default" started successfully

```
Set the environment variable `DOCKER_HOST` to `npipe:////./pipe/docker_engine`, e.g. for Powershell is `$env:DOCKER_HOST='npipe:////./pipe/docker_engine'`.

This should allow `docker-compose` and `docker compose` to interact with Podman. However it should be possible to use `podman compose` without this. Unfortunately Docker appears to be listening on `//./pipe/dockerDesktopLinuxEngine`, but Podman appears to expect it to use `npipe:////./pipe/docker_engine`.

Also try running `podman compose --version` to check which external compose provider is being used.

```
> podman compose --version

>>>> Executing external compose provider "C:\\Program Files\\Docker\\Docker\\resources\\bin\\docker-compose.exe". Please see podman-compose(1) for how to disable this message. <<<<

Docker Compose version v2.40.3-desktop.1
```
