### ISSUE TITLE
Manifest create has poor error message on conflict with image

### ISSUE THREAD

**Issue by c-kruse** [containers/podman#24537]
### Issue Description

When running podman manifest create with a list name that conflicts with an image in local storage, the error message contains unclear instructions.

Ex:
```
$ podman manifest create docker.io/debian:bookworm
Error: image name "docker.io/library/debian:bookworm" is already associated with image "d36ff...": that name is already in use, or use --replace to instruct Podman to do so.
```

My issue is with the last part: "that name is already in use, or use --replace to instruct Podman to do so.", which strikes me as mostly nonsense. --replace is not an option for manifest create, and the form of the statement makes me think that this could be leaking in from some other context.

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman pull docker.io/debian:bookworm
2. podman manifest create docker.io/debian:bookworm

### Describe the results you received

Error: image name "docker.io/library/debian:bookworm" is already associated with image "d36fff64533637911da97f82594d1733f7e4e7c112c78d168f516d1b0673e2ff": that name is already in use, or use --replace to instruct Podman to do so.

### Describe the results you expected

I am not really sure - I do not totally understand the relationship podman keeps in local storage between "manifests" (OCI image indexes?) and images (OCI image manifests?.)

A safe bet may be something like "that name is already in use, either remove the image or use a unique list name"

### podman info output

```yaml
# pay no mind to me being on arm64 - can reproduce across the board on fedora 41.
$ podman version
Client:       Podman Engine
Version:      5.2.5
API Version:  5.2.5
Go Version:   go1.23.2
Built:        Thu Oct 17 17:00:00 2024
OS/Arch:      linux/arm64
$ rpm -q podman
podman-5.2.5-1.fc41.aarch64
$ podman info
host:
  arch: arm64
  buildahVersion: 1.37.5
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.12-3.fc41.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.12, commit: '
  cpuUtilization:
    idlePercent: 96.6
    systemPercent: 1.02
    userPercent: 2.38
  cpus: 2
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: silverblue
    version: "41"
  eventLogger: journald
  freeLocks: 2047
  hostname: fedora
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
  kernel: 6.11.7-300.fc41.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 111263744
  memTotal: 4081864704
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.13.1-1.fc41.aarch64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.13.1
    package: netavark-1.13.0-1.fc41.aarch64
    path: /usr/libexec/podman/netavark
    version: netavark 1.13.0
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by baude** [comment]
That problem was introduced in https://github.com/containers/podman/blob/e07c31068f55b433da453de54295e4d3b09dc774/cmd/podman/root.go#L668

where the error is always being wrapped ... I don't think there are plans to add --replace to the manifest so I think it should be fixed as pointed out?

@nalind do you generally agree?

**Comment by nalind** [comment]
We've had "replace an image with a list that includes that image" on the to-do list as RUN-2047 for a while, but we haven't wired up `github.com/containers/common/libimage.ConvertToManifestList()` to anything yet.

**Comment by flypenguin** [comment]
well ... me kinda too :/ . no idea whats happening.

**Comment by scoulter** [comment]
Still seeing this incorrect message "that name is already in use, or use --replace to instruct Podman to do so" on "podman manifest create" command in 4.9.4.  It is very confusing, as noted above.

And yes, I realize this is an old version.  It's what we get on RH (OL) 8.

**Comment by andrewazores** [comment]
Seeing it with 5.7.1 as well.

**Comment by der-eismann** [comment]
Exists on 5.8.2 as well. Unfortunately https://github.com/podman-container-tools/buildah/issues/6639 was closed with no activity.
