### ISSUE TITLE
podman breaks if user account is renamed, cryptic error "database static dir ... does not match our static dir", fix is difficult

### ISSUE THREAD

**Issue by AdamWill** [containers/podman#24938]
### Issue Description

I inadvertently created my user account on a new (Fedora Silverblue) system as 'adam', not 'adamw'. So I renamed it and carried on. But when I came to do something with podman (which had obviously somehow created some initial config even though I hadn't directly done anything with it), it failed with a cryptic error:
```
Error: database static dir "/var/home/adam/.local/share/containers/storage/libpod" does not match our static dir "/var/home/adamw/.local/share/containers/storage/libpod": database configuration mismatch
```
It was rather difficult to fix this. The error doesn't tell you where the "database" in question is (or what "our" means, exactly). `podman system reset` and `podman system migrate` as root do not fix it. `podman info` as root doesn't clearly tell you where the databases are. Running commands as user with `podman --debug` doesn't tell you either.

In the end I had to poke around in the source to work out the db in question was in `/var/home/adamw/.local/share/containers/storage/db.sql`. Then to fix it, since there's no `sqlite3` on Silverblue and I couldn't enter a toolbox container because of this exact problem, I had to scp the file off to another system, fix several paths in it with sqlite3, then copy it back to the affected system. Surely there must be a better way?

### Steps to reproduce the issue

Steps to reproduce the issue
1. Install a Fedora Silverblue system, create the initial user, use the desktop briefly
2. Switch to single-user mode and rename the user
3. Boot normally, log in as the renamed user, try to use podman (or toolbox)

### Describe the results you received

`Error: database static dir "/var/home/adam/.local/share/containers/storage/libpod" does not match our static dir "/var/home/adamw/.local/share/containers/storage/libpod": database configuration mismatch`

### Describe the results you expected

Working podman

### podman info output

```yaml
doesn't seem relevant...this is Fedora Silverblue Rawhide with podman 5.3.1.
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

**Comment by Luap99** [comment]
This is expected. The podman db caches path on first use. Any path change later on will cause issues. This includes user name change or uid change as the uid is part of the runroot.
The main issue that we store a ton of full paths in the db, container configuration, their mount points, etc... most of them encoded in json blobs that are part of the db. So if we would ever have logic to deal with path changes they would need to be able to rewrite all paths which seems very difficult to do and then would likely result in ton of technical debt so we never did that.

We can certainly try to return better errors here and we really should get `podman system reset` fixed in such case to be able to recover these scenarios. 
cc @mheon

**Comment by mheon** [comment]
I wonder if we can relax the caching to allow the paths to be updated iff no containers, no pods, and no images are present? That might make things simpler.

Doesn't solve the error message issue, though.

**Comment by adoreparler** [comment]
This also happens if you try to change graphroot.

**Comment by nut-3** [comment]
I encountered this error today. Our organization uses AD auth, and today, my username format changed from `user@domain` to just `user`. I had to rename my home directory and adjust configurations. Unfortunately, Podman stopped working with this error.
I've managed to change all paths in the SQLite DB and all paths in the JSON configurations. Now everything is fine. Note that you need SQLite3 installed to make changes in the Podman DB.

1. I changed the username in the `/etc/subuid` and `/etc/subgid` files.

2. I changed all the paths in the `/home/<username>/.local/share/containers/storage/overlay-containers/*/userdata/config.json` files.

3. I changed the Podman main configuration paths:
```
sqlite3 ~/.local/share/containers/storage/db.sql
```
after that
```
update DBConfig set StaticDir='/home/<username>/.local/share/containers/storage/libpod', GraphRoot='/home/<username>/.local/share/containers/storage', VolumeDir='/home/<username>/.local/share/containers/storage/volumes' where ID=1;
```
4. Then I changed all the volume paths inside the DB:
```
update VolumeConfig set JSON = json_set(JSON, '$.mountPoint', replace(json_extract(JSON, '$.mountPoint'), '<OLD_USERNAME>', '<NEW_USERNAME>'));
```
5. This didn't help, so I changed the paths in other tables just in case:
```
update ContainerConfig set JSON = replace(JSON, '<OLD_USERNAME>', '<NEW_USERNAME>');
update ContainerState set JSON = replace(JSON, '<OLD_USERNAME>', '<NEW_USERNAME>');
```
6. I had to restart the machine, and all my containers started working again.

**Comment by gemelen** [comment]
The problem still exists, one has to modify paths in the db.sql in order to restore functionality after path change.

At least 'podman system reset' should really reset state.
