### ISSUE TITLE
Feature request: Podman on Centos8 distro on Windows WSL 2 on any Windows edition.

### ISSUE THREAD

**Issue by PavelSosin-320** [containers/podman#7548]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

kind feature

**Description**
Background:
After I have succeeded to run Docker on CentOS7 distro on Windows WSL2 without any additional software products like DockerDesktop I would like to run Podman on CentOS8.1 distro on Windows WSL2 available on any Windows edition, including OEM Home, as a standard feature. 
Expected added value:
Very low-cost, low footprint modern Container tool for any developer or user developing Linux containers on Windows machine.

The current state:
Docker - up and running and runs Theia backend without Docker Desktop using "stocked" Docker CE on CentOS7 distro. The absence of duplicated features and bloatware leads to a minimal footprint. 
CentOS8.1 distro - up and running from unofficial Centos 8.1 distro project. MS Store Official CentOS 8 distro is broken, possibly, due to a generic bug in the WSL distro installation. 
Podman - up and running
Gaps and showstoppers:
- lack of systemd support by WSL. Taking into account the level of pressure applied to the WSL team, expected to be solved soon. My docker daemon on CentOS7 I have to start manually. 
- lack of firewall and firewall management tools. WSL 2 is a very low-footprint, lightweight VM without its own Networking which uses NIC to expose all ports on the Windows host network surface. Network security duties are delegated to the Windows firewall. Without bridge between the Host network, WSL distro has nothing to protect.
It is the showstopper for Container networking. Docker Desktop and Docker CE on CentOS7 tolerate this problem if Selinux is disabled. Only Warning messaged are printed. Podman fails if iptables operations return error code, even if Selinux is disabled.
It happens both during the run and builds images (Theia)

**Steps to reproduce the issue:**

1. Install unofficial CentOS8.1 WSL distro from the GitHUB project

2. Install Podman using DNF

3. Copy Theia dockerfile and pull Theia image
4. Podman run Theia image
5. Podman build Theia dockerfile.

**Describe the results you received:**

Error messages from Container Networking plugin reporting that iptables are found, can't read chains, etc. 
**Describe the results you expected:**
Warning messages only if Podman runs inside WSL distro and Selinus is disabled.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Wondows 10 2004 May update.
Podman 
[PodmanInfoDebug.log](https://github.com/containers/podman/files/5179202/PodmanInfoDebug.log)
[PodmanInfoDebug.log.log](https://github.com/containers/podman/files/5179206/PodmanInfoDebug.log.log)

Version:            1.6.4
```

**Output of `podman info --debug`:**

```
see attached file
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Windows 10 WSL 2 Homebrew CentOS8,1 distro**

**Comment by zhangguanzhang** [comment]
the latest version is 2.0.6

**Comment by rhatdan** [comment]
Can you just use --net=host?

@baude @mheon Ideas?

**Comment by vrothberg** [comment]
I also think that using the host network may be the best/cheapest way on WSL. Starting with Podman v2.0, we can set the default in the `containers.conf` (netns="host").

You can install more recent versions of Podman via the repositories we maintain on the Open Build Service as described on [podman.io](https://podman.io/getting-started/installation).

**Comment by mheon** [comment]
Given that Docker + Libnetwork should be working on WSL2, I would expect that whatever is necessary to enable full networking should be present. It may be a pain to get it enabled and working, though.

**Comment by PavelSosin-320** [comment]
"Stock" Docker works on CentOS7. 
Podman as a single container runner is not so valuable. How containers that belong to the same pod will communicate? It is impossible to use ----network option with  podman pod create to bridge Pod with WSL VM  eth0 interface. What is the host network in such a case, WSL VM or Windows host? 
All ports on WSL eth0 have translated automatically to the Windows host but 1st Pod has to be connected to eth0.

**Comment by lsm5** [comment]
@PavelSosin-320 are things any better if you use podman 2.1.1 from the [Kubic project repos](https://podman.io/getting-started/installation) for CentOS 8?

**Comment by PavelSosin-320** [comment]
Meanwhile, Microsoft pushed the WSL Linux Kernel forward to Kernel Version: **4.19.128**-Microsoft-standard and I upgraded my CentOS WSL distro to 8.2.
The same Network issue persists: attempt to use iptables. The recent Docker Desktop version issues warnings:
![image](https://user-images.githubusercontent.com/54495912/95183121-2e841e80-07ce-11eb-8e60-9f166a65f3ad.png)
although Docker Desktop distro does support iptables according to Docker's distro iptables -t nat -S -wait output:
![image](https://user-images.githubusercontent.com/54495912/95183216-54112800-07ce-11eb-9470-d1dc87ec11ad.png)

Maybe, this is the right decision? It can't be per Network configuration because it affects all networks of the same kind as in the Docker's case.

**Comment by PavelSosin-320** [comment]
Meanwhile, Microsoft pushed the WSL Linux Kernel forward to Kernel Version: **4.19.128**-Microsoft-standard and I upgraded my CentOS WSL distro to 8.2.
The same Network issue persists: attempt to use iptables. The recent Docker Desktop version issues warnings:
![image](https://user-images.githubusercontent.com/54495912/95183121-2e841e80-07ce-11eb-8e60-9f166a65f3ad.png)
although Docker Desktop distro does support iptables according to Docker's distro iptables -t nat -S -wait output:
![image](https://user-images.githubusercontent.com/54495912/95183216-54112800-07ce-11eb-9470-d1dc87ec11ad.png)

Maybe, this is the right decision? It can't be per Network configuration because it affects all networks of the same kind as in the Docker's case.

**Comment by PavelSosin-320** [comment]
Meanwhile, Microsoft pushed the WSL Linux Kernel forward to Kernel Version: **4.19.128**-Microsoft-standard and I upgraded my CentOS WSL distro to 8.2.
The same Network issue persists: attempt to use iptables. The recent Docker Desktop version issues warnings:
![image](https://user-images.githubusercontent.com/54495912/95183121-2e841e80-07ce-11eb-8e60-9f166a65f3ad.png)
although Docker Desktop distro does support iptables according to Docker's distro iptables -t nat -S -wait output:
![image](https://user-images.githubusercontent.com/54495912/95183216-54112800-07ce-11eb-9470-d1dc87ec11ad.png)

Maybe, this is the right decision? It can't be per Network configuration because it affects all networks of the same kind as in the Docker's case.

**Comment by PavelSosin-320** [comment]
Yes, I already installed and playing with Podman from Kubic project for Ubuntu 20.04. WSL distro. The 1st impression is great. My problems are
1. The Microk8s from the Kubic project conflicts with Docker Desktop.
2. I'm old Redhatter and prefer to use RedHat's tools
3. The Centos 8 distro in Microsoft Store is broken. I had to install CentOS 8.1 from Github and upgrade it to 8.2 manually. I've stopped to get upgrades since this update. 
4. CentOS 8.+ uses nftables instead of old iptables. It causes forward compatibility issue for CNI implementation. CNI doesn't work now and further upgrade of Podman version are impossible.

**Comment by mheon** [comment]
The CNI issue is interesting, because we spent a lot of timing making sure CNI and nftables worked together before 8 was released - it should work without issue. I have, however, heard of a lot of network issues on WSL2 in general, though - iptables not functioning properly (which can be extrapolated to nftables not working properly, probably?)

**Comment by mheon** [comment]
More details on the network issues in particular would be appreciated, though. Assuming it is WSL, we've never been able to track down exactly what is breaking. I can't guarantee we can fix on our end (may well turn out to be WSL2 kernel settings) but it would be nice to know for sure.

**Comment by PavelSosin-320** [comment]
I succesfully run Podman on Ubuntu 20.04 distro provided by Kube project. This distro still uses iptables ver 1.8.4 legacy. The trck maybe that is WSL network is not bridged to the host network. It uses NIC, i.e all servers have to listen all interfaces, eth0 and localhost of WSL VM.
My smoke tests didn't face any issues - everything works nice up to Pod containing nginx.
The main difference that in the Kube project Ubuntu 20.04 distro uses systemd via some trick. Other distros use /init.
The Kernel is the same Microsoft Kernel 4.9. Maybe, capability to use the correct iptables / nftables can solve the problem.
When nftables is available iptables invocation returns code 4 and some warnings saying that nft shall be used instead.
Unfortunatly, the recent CentOS8.2 WSL distro is not available and I have to work with yuk7 8.1 rolled forward to 8.2 but with old Microsoft Kernel. Replace the Kernel for distro is not so big work and I can test it but not build it.

**Comment by rhatdan** [comment]
Any more updates on Podman support on WSL2?

**Comment by PavelSosin-320** [comment]
@mheon I found recently that MS released the Linux kernel 5.4 internally. Unfortunately, as it frequently happens my attempt to upgrade WSL Kernel from MS 4.9 to 5.4 on 2 laptops failed. Podman 2.1.1 and K8s on Ubuntu 20.04 work but use iptables ver 1.8 legacy. In other words, CNI is OK but RedHat's decision to bundle RHEL8 and CentOS8 with Podman and switch from iptables to nftables in the same time without release WSL2 distro to Microsoft store causes many issues. I hope that most of them are not exactly Podman issues and, even can be already solved in Podman RHEL 8.2 & v2.2-RC-01. But the real problem is that the distros in Microsoft store are managed by Microsoft store and their quality is unpredictable like CentOS8 distro and Linux Kernel 5.4

**Comment by PavelSosin-320** [comment]
[RedHat recommendations about firewall to use ](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/securing_networks/getting-started-with-nftables_securing-networks)
The iptables utility is deprecated in Red Hat Enterprise Linux 8. Use instead nftables. In the CentOS8 too?
Indeed, in my home-made CentOS8 iptables already absent.

**Comment by rhatdan** [comment]
At this point is this really a Podman issue, or more an issue with how distros and Microsoft work?  I know that @baude has been successful with WSL 2 and podman.

**Comment by PavelSosin-320** [comment]
I think that following the recent RedHat announcement it is not relevant anymore and CentoOS-stream with pre-installed Podman & Kubernetes WSL distro is expected soon.
