### ISSUE TITLE
A change to netns /etc/resolv.conf is not present in podman run container

### ISSUE THREAD

**Issue by bbros-dev** [containers/podman#7817]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When I change the content of /etc/resolv.conf in a netns and then pass that netns to `podman run`, the change is not present in the container.

**Steps to reproduce the issue:**

1. Create a netns `gitea-drone` as Described on the [WireGuard netns page](https://www.wireguard.com/netns/)

2. Edit the netns `gitea-drone` to make the `/etc/resolv.conf` point to a new nameserver:

```bash
$ sudo ip netns exec gitea-drone bash
# vim /etc/resolv.conf
nameserver 10.200.200.1
```

3. Launch rootful podman pointing to netns `gitea-drone`

```bash
sudo podman run --rm -it --user 5000 --network=ns:/var/run/netns/gitea-drone gitea/gitea:1.12.4 bash
$ cat /etc/resolv.conf
search Home
nameserver 192.168.1.1
```

**Describe the results you received:**

`nameserver 192.168.1.1`

**Describe the results you expected:**

`nameserver 10.200.200.1`

**Additional information you deem important (e.g. issue happens only occasionally):**

Reproducible

**Output of `podman version`:**

```
$ podman --version
podman version 2.1.0
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: '
  cpus: 2
  distribution:
    distribution: ubuntu
    version: "18.04"
  eventLogger: journald
  hostname: desktop.local.lan
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.15.0-117-generic
  linkmode: dynamic
  memFree: 607318016
  memTotal: 16680198144
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.4
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
  swapFree: 4294164480
  swapTotal: 4294963200
  uptime: 148h 21m 13.17s (Approximately 6.17 days)
registries:
  search:
  - docker.io
store:
  configFile: /home/hedge/.config/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 0
    stopped: 3
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/hedge/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 17
  runRoot: /run/user/1000/containers
  volumePath: /home/hedge/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 0
  BuiltTime: Thu Jan  1 10:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.1.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ apt list podman 
Listing... Done
podman/unknown,now 2.1.0~1 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes, checked trooubleshooting.
No haven't tried latest release

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical

**Comment by bbros-dev** [comment]
Just to acknowledge there is a `--dns=<ip>` command line workaround for anyone else journeying along this path:

```bash
sudo podman run --rm -it --user 5000 --dns=10.200.200.1 --network=ns:/var/run/netns/gitea-drone gitea/gitea:1.12.4
```

**Comment by rhatdan** [comment]
@QiWang19 PTAL

**Comment by QiWang19** [comment]
Failed to replicate the issue, this should have been fixed upstream.
```
$ podman --version
podman version 2.2.0-dev
$ sudo ip netns add gitea-drone
$ sudo ip link add wg0 type wireguard
$ sudo ip link set wg0 netns gitea-drone
$ sudo ip netns exec gitea-drone bash
# vim /etc/resolv.conf
# exit
exit
$ sudo podman run --rm -it --user 5000 --network=ns:/var/run/netns/gitea-drone gitea/gitea:1.12.4 bash
bash-5.0$ cat /etc/resolv.conf
nameserver 10.200.200.1
bash-5.0$ 

```

**Comment by bbros-dev** [comment]
Hmm, there seem to have been 4 steps skipped in the upstream (WireGuard) instructions?:

```bash
# ip -n container addr add 192.168.4.33/32 dev wg0
# ip netns exec container wg setconf wg0 /etc/wireguard/wg0.conf
# ip -n container link set wg0 up
# ip -n container route add default dev wg0
```
Are we really sure these don't impact?
Note the setup using wg0.conf should complain about the Address and Names server lines in wg0.conf, so I commented these out and setup then proceeds without error.

**Comment by bbros-dev** [comment]
Hmm, I can reproduce my description of behavior on fresh Ubuntu 18.04 on Vultr, but looks like it may be ubuntu specific.

**Comment by ciandonovan** [comment]
Issue still present on Ubuntu 22.04 Host and Ubuntu 22.04 container from Dockerhub.

After switching networks from 192.168.0.0 to 192.168.1.0 on the host, the container's `/etc/resolv.conf`:

```
nameserver 192.168.0.1
```

and the host's:

```
# This is /run/systemd/resolve/stub-resolv.conf managed by man:systemd-resolved(8).
# Do not edit.
#
# This file might be symlinked as /etc/resolv.conf. If you're looking at
# /etc/resolv.conf and seeing this text, you have followed the symlink.
#
# This is a dynamic resolv.conf file for connecting local clients to the
# internal DNS stub resolver of systemd-resolved. This file lists all
# configured search domains.
#
# Run "resolvectl status" to see details about the uplink DNS servers
# currently in use.
#
# Third party programs should typically not access this file directly, but only
# through the symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a
# different way, replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 127.0.0.53
```

with `resolvectl` showing:

```
Link 4 (wlx00c0cab02341)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 192.168.1.1
       DNS Servers: 192.168.1.1
        DNS Domain: home
```
