### ISSUE TITLE
Cannot perform  "podman build" within sshfs-mounted directory

### ISSUE THREAD

**Issue by usury** [containers/podman#8338]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Unable to perform **$> podman build** within _sshfs-mounted_ directory.

The error seems _similar_ to https://github.com/containers/buildah/issues/2774
However, that bug report describes building an image within a container. This bug report describes building an image directly on the container host.

**Steps to reproduce the issue:**
```
otheruser@otherhost $> tree ~/images/myimage
    myimage
    ├── Dockerfile
    ├── docker-php-ext-configure
otheruser@otherhost $> cat ~/images/myimage/Dockerfile
    FROM debian:buster-slim
    COPY docker-php-ext-*  /usr/local/bin/

regularuser@containerhost $> sshfs otheruser@otherhost:images/ ~/images
regularuser@containerhost $> cd ~/images/myimage
regularuser@containerhost $> podman build .
```

**Describe the results you received:**
Failure building otherwise valid image
```
STEP 2: COPY docker-php-ext-*  /usr/local/bin/
copier: get: "/docker-php-ext-configure": error getting extended attributes for "/docker-php-ext-configure": error listing extended attributes of "/docker-php-ext-configure": operation not supported
```
**Describe the results you expected:**
Successful image build

**Additional information you deem important (e.g. issue happens only occasionally):**
Happens consistently and reproducably.

If the sshfs-mounted directory is _copied_ to containerhost, the build occurs without error
The copy-the-dir approach is a work-around, but not a good solution for me
```
    $> cp -a ~/images ~/images-local
    $> cd ~/images-local/myimage
    $> podman build .
```

**Output of `podman version`:**
```
        Version:      2.1.1
        API Version:  2.0.0
        Go Version:   go1.14
        Built:        Wed Dec 31 16:00:00 1969
        OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**
```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: '
  cpus: 4
  distribution:
    distribution: debian
    version: "10"
  eventLogger: journald
  hostname: arachne
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 2000
      size: 1
    - container_id: 1
      host_id: 100001
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 2000
      size: 1
    - container_id: 1
      host_id: 100001
      size: 65536
  kernel: 4.19.0-10-amd64
  linkmode: dynamic
  memFree: 369057792
  memTotal: 2091732992
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.0~rc6+dfsg1
      commit: 1.0.0~rc6+dfsg1-3
      spec: 1.0.1
  os: linux
  remoteSocket:
    path: /run/user/2000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.4
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
  swapFree: 746057728
  swapTotal: 1073737728
  uptime: 184h 14m 26.29s (Approximately 7.67 days)
registries:
  search:
  - docker.io
  - quay.io
version:
  APIVersion: 2.0.0
  Built: 0
  BuiltTime: Wed Dec 31 16:00:00 1969
  GitCommit: ""
  GoVersion: go1.14
  OsArch: linux/amd64
  Version: 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**
```
podman/unknown,now 2.1.1~2 amd64 [installed]
podman/unknown 2.1.1~2 arm64
podman/unknown 2.1.1~2 armhf
podman/unknown 2.1.1~2 ppc64el
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Container host is a VirtualBox VM running Debian Buster
VirtualBox VM host is Fedora 32
podman packages installed from OpenSuse repo
**$> cat "/etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"**
```
## "Kubic" repo from "OpenSuse" for "podman" packages since they aren't in Debian 10 (buster) repos
deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/ /
```
**$> cat /etc/os-release** 
`PRETTY_NAME="Debian GNU/Linux 10 (buster)"`

**Comment by mheon** [comment]
@giuseppe I'm guessing this is a fuse-overlay issue?

**Comment by rhatdan** [comment]
I believe @nalind might have just made a change to buildah to ignore certain errors in COPY/ADD when Xattrs are not supported.  This might already be fixed in master branch.

**Comment by rhatdan** [comment]
https://github.com/containers/buildah/pull/2778

**Comment by nalind** [comment]
Agreed, I think https://github.com/containers/buildah/pull/2778 fixes this.

**Comment by mheon** [comment]
Looks like we'll pick it up when we vendor Buildah v1.18

**Comment by monken** [comment]
Just tried building a container from a 9p filesystem with buildah 1.18.0 and I'm still getting this error:

```
error getting extended attributes for "/somefile": error listing extended attributes of "/somefile": timer expired
```

**Comment by zhangguanzhang** [comment]
> Just tried building a container from a 9p filesystem with buildah 1.18.0 and I'm still getting this error:
> 
> ```
> error getting extended attributes for "/somefile": error listing extended attributes of "/somefile": timer expired
> ```
I test this, work correct, how reproduce your error
```
$ mkdir /root/sshfs
$ sshfs 10.226.45.86:/root/test /root/sshfs/
The authenticity of host '10.226.45.86 (10.226.45.86)' can't be established.
ECDSA key fingerprint is SHA256:d6zNoaohkZG/QFu/bcJ+nCPwdfKtDwnrK9mSAeiHASo.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
root@10.226.45.86's password: 
$ ll /root/sshfs/
total 4
-rw-r--r-- 1 root root 48 Dec 14 11:40 Dockerfile
$ cd /root/sshfs/
$ ll
total 4
-rw-r--r-- 1 root root 48 Dec 14 11:40 Dockerfile
$ cat Dockerfile 
FROM docker.io/library/alpine
COPY Dockerf* /
$ podman version
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.13.15
Built:        Wed Dec  9 05:10:52 2020
OS/Arch:      linux/amd64
$ podman build .
STEP 1: FROM docker.io/library/alpine
STEP 2: COPY test* /
--> Using cache 6c2e2856577587edbfa36be039fde5e73d60c324dcc36d431abcc8e841d383d3
--> 6c2e2856577
6c2e2856577587edbfa36be039fde5e73d60c324dcc36d431abcc8e841d383d3
```

**Comment by monken** [comment]
Could be an issue with the 9p server then. In any case, I think Buildah should be less strict when it comes to these errors. Building with `docker` works just fine.

**Comment by rhatdan** [comment]
Well podman build including buildah 1.18.0 so I am closing this issue, @monken your issue looks different but I believe it is involved in the underlying file system and not something podman or buildah can deal with.  Maybe fuse-overlay is having an issue.  @giuseppe WDYT?
